### ISSUE TITLE
OWT Does not use GPU Accelerator 

### ISSUE THREAD

**Issue by iPPLE** [open-webrtc-toolkit/owt-server#1036]
OWT-Server : Latest version
Media Server : Latest version
Ubuntu 18.04.5 LTS Kernel 5.4.0-77-generic
GPU : GeForce GTX 1070
CPU : Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
NodeJS : v10.24.1

Follow this instruction for OWT Build and Install:
https://github.com/open-webrtc-toolkit/owt-server
https://github.com/open-webrtc-toolkit/owt-server/blob/master/doc/servermd/Server.md

Follow this instruction for Media SDK Build and Install:
https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-Ubuntu

Note : I don't have any error in all the logs... plz help to provide a clearer instruction on how to link from OWT Video agent to GPU Accelerator. It seems my GPU is not being used at all even i tried to replicate many participants in a room with all kind of video codes.
<img width="563" alt="Screen Shot 2021-07-08 at 4 49 02 PM" src="https://user-images.githubusercontent.com/8819027/124901764-81645e00-e00c-11eb-8aac-eb87b0a9c4fc.png">
<img width="357" alt="Screen Shot 2021-07-08 at 4 52 13 PM" src="https://user-images.githubusercontent.com/8819027/124902176-e6b84f00-e00c-11eb-9ddc-c75a0bbe06f7.png">

My GPU is working properly i can tell by perform a gpu_burn tools here https://github.com/wilicc/gpu-burn
<img width="719" alt="Screen Shot 2021-07-08 at 4 56 03 PM" src="https://user-images.githubusercontent.com/8819027/124902757-7231e000-e00d-11eb-85e7-f3a5b1f0a8e0.png">

Thanks.

**Comment by starwarfan** [comment]
Hi,
Have you built the hardware version video-mixer/transcoder before packing?
`scripts/build.js -t video-mixer-msdk -t video-transcoder-msdk`

**Comment by iPPLE** [comment]
No i didn't and now i tried all over again  still no luck !.. anyway i don't see this in the document...

git clone https://github.com/open-webrtc-toolkit/owt-server.git

. Built the hardware version video-mixer/transcoder before packing
> scripts/build.js -t video-mixer-msdk -t video-transcoder-msdk

. Interactive
> scripts/installDeps.sh

. Non-interactive
> scripts/installDepsUnattended.sh

. BUILD OWT CLIENT JAVASCRIPT

> git clone https://github.com/open-webrtc-toolkit/owt-client-javascript.git
>
> cd owt-client-javascript/
>
> npm install
>
> cd scripts/
>
> npm install -g grunt-cli
>
> grunt

. BUILD RELEASE PACKGGE
> scripts/pack.js -t all --install-module --app-path ~/owt-client-javascript/dist/samples/conference

. Configure certificate for portal, management_api, management_console, webrtc_agent, apps
. InitCert.js in all components

. INSTALL MEDIA SDK
https://github.com/Intel-Media-SDK/MediaSDK/wiki/Build-Media-SDK-on-Ubuntu

> ~/owt-server/dist/video_agent/install_ffmpeg.sh
> ~/owt-server/dist/audio_agent/compile_ffmpeg_with_libfdkaac.sh
> ~/owt-server/dist/bin/init-all.sh --deps --hardware
> [video_agent/audio_agent/webrtc_agent/recording_agent/streaming_agent/sip_agent/analytics_agent]/install_deps.sh
> video_agent/install_deps.sh --hardware
> video_agent/init.sh --hardware

. Run the following commands to launch agent worker
> ./bin/daemon.sh start [conference-agent/webrtc-agent/streaming-agent/audio-agent/video-agent/analytics-agent/recording-agent/sip-agent]

> ~/owt-server/dist/bin/start-all.sh

Do i have missed anything else ?

**Comment by qwu16** [comment]
Please refer to https://github.com/Intel-Media-SDK/MediaSDK/blob/intel-mediasdk-21.2.3/doc/mediasdk_release_notes.md#System_Requirements for Intel Media SDK supported hardware.

**Comment by iPPLE** [comment]
Ok.. thank you.. my Graphic Adapter is not Intel.. so it is not supported.
