### ISSUE TITLE
Running install_openh264.sh script fails to install

### ISSUE THREAD

**Issue by jimmy-huang** [open-webrtc-toolkit/owt-server#104]
When you try to run the this script ./source/agent/video/install_openh264.sh, it will fail to install since the lib directory doesn't exist.

This is the output:
Download libopenh264-1.7.0-linux64.4.so success.
mv: cannot stat '/owt-server/source/agent/video/lib/libopenh264.so.4': No such file or directory
mv: cannot move 'libopenh264-1.7.0-linux64.4.so' to '/owt-server/source/agent/video/lib/libopenh264.so.4': No such file or directory

**Comment by starwarfan** [comment]
Hi, what will cause 'lib' directory missing?
I cannot reproduce this yet.

**Comment by jimmy-huang** [comment]
@starwarfan I was running it inside a docker container right after ./scripts/installDepsUnattended.sh, and that's when I saw the error, but then @qwu16 told me that the actual script should be ran in ./dist/video_agent/ where the JS is already packed.  So I think this may not be intended to run as is, so you can close it.

**Comment by starwarfan** [comment]
Please run install_openh264.sh after pack.js
