### ISSUE TITLE
Unable to install dependencies in OWT Server v.5.0 (video_agent)

### ISSUE THREAD

**Issue by Chandramouli-P** [open-webrtc-toolkit/owt-server#1050]
Hello,

Operating System: Ubuntu v.18.04 server
Node version: v10.24.1
NPM version: v6.14.12

After building OWT server v.5.0, I tried to install dependencies in video_agent. I tried in different ways, but unable to install. Please find the below commands that I tried:

chandramouli@chandramouli:~/owt-server-dist-v5.0/dist/video_agent**$ sudo ./install_deps.sh**
sudo: ./install_deps.sh: command not found

chandramouli@chandramouli:~/owt-server-dist-v5.0/dist/video_agent**$ sudo su -**
root@chandramouli:~# cd /home/chandramouli/owt-server-dist-v5.0/dist/video_agent/
root@chandramouli:/home/chandramouli/owt-server-dist-v5.0/dist/video_agent**# ./install_deps.sh**
-su: ./install_deps.sh: Permission denied

root@chandramouli:/home/chandramouli/owt-server-dist-v5.0/dist/video_agent**# sh install_deps.sh** 
install_deps.sh: 9: install_deps.sh: [[: not found
install_deps.sh: 71: install_deps.sh: shopt: not found
install_deps.sh: 74: install_deps.sh: Syntax error: "(" unexpected (expecting ")")

root@chandramouli:/home/chandramouli/owt-server-dist-v5.0/dist/video_agent**# bash install_deps.sh --hardware**
install_deps.sh: line 36: /home/chandramouli/owt-server-dist-v5.0/dist/video_agent/detectOS.sh: Permission denied
Unsupported platform...
install_deps.sh: line 92: /home/chandramouli/owt-server-dist-v5.0/dist/video_agent/install_ffmpeg.sh: Permission denied

I haven't faced any issues in the previous versions of OWT. Hence, request you to help us in resolving the issue.

Thank you.

Best Regards,
Chandramouli.

**Comment by kurapatijayaram** [comment]
+1

**Comment by Chandramouli-P** [comment]
Hello Team,

Any update would be appreciated. Thank you.

Best Regards,
Chandramouli.

**Comment by dannyZhou** [comment]
do not use `sh`, use `bash`.
 try to add executable permission of `detectOS.sh` `install_ffmpeg.sh`
`chmod +x detectOS.sh` and `chmod +x install_ffmpeg.sh`
