### ISSUE TITLE
Uncaught (in promise) Error: No QUIC connection available.

### ISSUE THREAD

**Issue by CongyueZhang** [open-webrtc-toolkit/owt-server#1058]
Got this error in the console, I have no idea about it. Could you please give some hint? Thank you so much.
![20210806154726](https://user-images.githubusercontent.com/53400587/128475845-acf16adb-5911-47f1-ae3c-6c201676d74d.jpg)

**Comment by CongyueZhang** [comment]
Fixed it. It is because I didn't start Chrome with flag --enable-experimental-web-platform-features. Could you please put it in the quic-programming-guide.md?

**Comment by jianjunz** [comment]
Hi,

This flag is described in [webtransport.md](https://github.com/open-webrtc-toolkit/owt-client-javascript/blob/d1ef66b99ccffa71df4710828d8906e6d8551670/docs/design/webtransport.md) of JavaScript SDK as it only applies to JavaScript clients.

**Comment by Kmtest-rgb** [comment]
> Fixed it. It is because I didn't start Chrome with flag --enable-experimental-web-platform-features. Could you please put it in the quic-programming-guide.md?

Hi did you build the owt-server and owt-javascript client from source ? Can you please give me the steps and which branch / version from github you are using as I am getting the same error even after launching chrome with the flag --enable-experimental-web-platform-features
