### ISSUE TITLE
录制forward流 偶尔会出现timeout

### ISSUE THREAD

**Issue by 516131179** [open-webrtc-toolkit/owt-server#107]
1，调用restapi 先获得流的信息， 然会对forward流进行录制， 
2， 偶尔会有timeout   ， 默认设置timeout是3s， 如果设置为6s，timeout概率变小，但是还是会出现timeout。（合流没发现timeout）
3， 此外timeout可能发生在recording最开始订阅流的阶段（这回导致视频文件不存在）， 也可能出现在订阅流的过程中（这会导致录制中断）。

**Comment by 516131179** [comment]
1:可能是推流时间太短， 录制的时候没有获得关键帧
2：可能推流的过程中同一条流网络异常有中断，中断时间超过录制timeout时间。

**Comment by daijh** [comment]
@516131179 you are right.

1.  Recording will wait for the first video key frame, until timeout. The timeout error usually happens in 'Forward' mode, as end-point (rtsp-in/rtmp-in)does not timely respond for RTCP 'FIR' feedback.
2. If no frames available in 2000ms during recording, the frame source connection is considered as broken and recording stops automatically.

**Comment by 516131179** [comment]
请问：如果我想保证我的forward流被录制成功（推流时间可以限制很长），那我应该如何避免timeout的出现 ，  谢谢@daijh

**Comment by xiandeatintel** [comment]
@516131179 Then you need to make sure 1) your publisher can respond to key-frame-requests; 2) the audio/video stream from publisher to server will NOT be disruputed for longer than 2000ms as @daijh said.

Please type in English next time when you need to raise an issue, thanks.
