### ISSUE TITLE
Bug for audio only views in rooms with a/v views

### ISSUE THREAD

**Issue by schlypel** [open-webrtc-toolkit/owt-server#1076]
I create a room with different video resolutions available. In this room I have multiple views, some with video, some without.
The views without audio don't work anymore, if the room contains at least on view, that is not audio only.
This only happens if a view with video has specific resolutions set.

This was introduced in the 5.x version, in 4.3.x it worked.

**Comment by Phillipip** [comment]
Unfortunately, the problem still exists. Does anyone have a solution?
