### ISSUE TITLE
Unable to compile "svtHevcEncoder" file

### ISSUE THREAD

**Issue by Chandramouli-P** [open-webrtc-toolkit/owt-server#1099]
Hello,

Please find the environment below:

Intel OWT Server v.5.0
Operating System: Ubuntu 18.04 (64-bit) Server
NodeJS Version: v10.24.1
NPM Version: 6.14.12
Firewall: All ports are completely opened in the firewall and as well as in the server also

I installed all necessary libraries and dependencies for hardware acceleration support. But, after executing "sudo ./compile_svtHevcEncoder.sh" command, I am getting the below errors:

([ 31%] Linking C static library ../../../Release/lib/libASM_SSE2.a
/usr/bin/ar: CMakeFiles/ASM_SSE2.dir/EbGatherSaoStatistics16bit_SSE2.asm.o: No such file or directory
Source/Lib/ASM_SSE2/CMakeFiles/ASM_SSE2.dir/build.make:376: recipe for target 'Release/lib/libASM_SSE2.a' failed
make[2]: *** [Release/lib/libASM_SSE2.a] Error 1
CMakeFiles/Makefile2:294: recipe for target 'Source/Lib/ASM_SSE2/CMakeFiles/ASM_SSE2.dir/all' failed
make[1]: *** [Source/Lib/ASM_SSE2/CMakeFiles/ASM_SSE2.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
~/Release-v5.0/video_agent)

Hence, request you to help me to resolve the above issue. Thank you.

Best Regards,
Chandramouli.

**Comment by starwarfan** [comment]
Hi,
You failed to compile SVTHevc. We don't have this issue. Maybe you could try to remove the svt_hevc_encoder and re-run the commands.

**Comment by Chandramouli-P** [comment]
Hello,

I am able to compile it successfully. Thank you.

Best Regards,
Chandramouli.
