### ISSUE TITLE
Cannot compile because of libre (both centos/ubuntu)

### ISSUE THREAD

**Issue by kekkokk** [open-webrtc-toolkit/owt-server#130]
![Screen Shot 2019-05-20 at 16 54 44](https://user-images.githubusercontent.com/15072723/58031142-1a2f7b00-7b20-11e9-84b9-f629e1e36438.png)

Happens on both centos 7 and ubuntu 18.04

**Comment by starwarfan** [comment]
#135 should fix this, you can update your branch and have a try

**Comment by xiandeatintel** [comment]
@kekkokk Please verify the operation @starwarfan provided.
