### ISSUE TITLE
录屏异常服务端一直录屏导致没有办法推流

### ISSUE THREAD

**Issue by SirZiWang** [open-webrtc-toolkit/owt-server#1322]
录屏异常时，服务端没有收到结束录屏的信令，服务端一直生成黑屏的视频。最终导致其它会议没有客户端没有办法推流，只有重启服务才会正常进行视频会议，有啥好的方式，如果异常不推流直接停止录屏。

**Comment by starwarfan** [comment]
Is this client side screen capture error?
When screen sharing fails, you can detect error on client side and call server side API to stop streaming.
