### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by starnightcyber** [open-webrtc-toolkit/owt-server#138]
Installation failed following git repo readme:
scripts/build.js -t mcu --check https://github.com/open-webrtc-toolkit/owt-server/issues/20

Follow the official site guideline, https://software.intel.com/en-us/articles/intel-collaboration-suite-for-webrtc
and access 3004 port,  i can see nothing but blank window, maybe installation failed either.

Anybody can help me with the installation.

**Comment by starwarfan** [comment]
Hi,
The quic addon failure does not matter if you don't use it. You may need update your repo.

**Comment by starnightcyber** [comment]
Finally succeed!
some useful materials :
https://software.intel.com/en-us/articles/intel-collaboration-suite-for-webrtc
and a blog in chinese
https://www.cnblogs.com/Hi-blog/p/How-To-Install-Intel-CS-WebRTC-On-Ubuntu.html
To install Intel_CS_WebRTC.v4.2, you need right version of node 8.11.1(prefer) and boost 1.65.1

**Comment by xiandeatintel** [comment]
Resolved.
