### ISSUE TITLE
OWT4.2 Background Configuration SIP Server, SIP normal use, apply this operation will make the SIP password encrypted, restart will lead to sip registration is not up.

### ISSUE THREAD

**Issue by cisco6** [open-webrtc-toolkit/owt-server#143]
OWT4.2 Background Configuration SIP Server, SIP normal use, apply this operation will make the SIP password encrypted, restart will lead to sip registration is not up.

**Comment by xiandeatintel** [comment]
Addressed by:
[https://github.com/open-webrtc-toolkit/owt-server/pull/144](url)
