### ISSUE TITLE
Dockerfile?

### ISSUE THREAD

**Issue by Bhlowe** [open-webrtc-toolkit/owt-server#16]
Is there a Dockerfile for building owt-server? I'm getting a few compile errors and using Docker as a standardized way to build a binary would be nice.

I started writing one.. and happy to share it.. But its getting stuck running the scripts/build.js building the webrtc code.. I think it is trying to build licode, but its missing the r_types.h header file.

Which ubuntu is best? 

Is there a demo server somewhere? 

FYI, I'm mostly interested in IP Camera RTSP broadcasting to 0 to N viewers. Saw your server supports RTSP, but not sure if it supports rtsp feeds as a webrtc source. 

Thanks!

**Comment by justinchoi97** [comment]
I am interested in this question too. Further following your question, can this server to RTMP -> webRTC with HEVC?

**Comment by daijh** [comment]
@Bhlowe owt-server accepts RTSP input, and forwards to multiple webrtc endpoints.

@justinchoi97 this server accepts RTMP HEVC input, and forward to multiple webrtc endpoints with HEVC supported; Or this server is able to trans-code to H264/VP8/VP9 for those webrtc endpoints without HEVC supported;

**Comment by justinchoi97** [comment]
@daijh wow impressive. As originally asked by @Bhlowe , is there a plan to make a dockerfile available from the dev team? That would be really handy. Thanks!

**Comment by qwu16** [comment]
@Bhlowe @justinchoi97  We have dockerfile files with MCU build environment for internal use only currently and we will open source it later.

**Comment by Bhlowe** [comment]
I posted my first draft of a Dockerfile here:
https://github.com/Bhlowe/owt-server/blob/master/Dockerfile

If you run it using: 
`docker build -t owt-server . `

It fails building the scripts/build.js making webrtc. 

```
../WebRtcConnection.cc:543:16: error: 'using element_type = class erizo::WebRtcConnection {aka class erizo::WebRtcConnection}' has no member named 'removeRemoteCandidate'; did you mean 'addRemoteCandidate'?
   bool r = me->removeRemoteCandidate(mid, sdpMLine, sdp);
...
../WebRtcConnection.cc:361:17: error: 'class erizo::IceConfig' has no member named 'ip_addresses'
       iceConfig.ip_addresses = ipAddresses;
```

Any fix suggestions appreciated!

Also, anyone have a demo of this software running they can share that features live video?

**Comment by laowangnj** [comment]
> I posted my first draft of a Dockerfile here:
> https://github.com/Bhlowe/owt-server/blob/master/Dockerfile
> 
> If you run it using:
> `docker build -t owt-server . `
> 
> It fails building the scripts/build.js making webrtc.
> 
> ```
> ../WebRtcConnection.cc:543:16: error: 'using element_type = class erizo::WebRtcConnection {aka class erizo::WebRtcConnection}' has no member named 'removeRemoteCandidate'; did you mean 'addRemoteCandidate'?
>    bool r = me->removeRemoteCandidate(mid, sdpMLine, sdp);
> ...
> ../WebRtcConnection.cc:361:17: error: 'class erizo::IceConfig' has no member named 'ip_addresses'
>        iceConfig.ip_addresses = ipAddresses;
> ```
> Any fix suggestions appreciated!
> 
> Also, anyone have a demo of this software running they can share that features live video?

that means your licode source hasn't been patched. your git name and email should be set first. see installDeps.sh

**Comment by Bhlowe** [comment]
That helped!
I updated my dockerfile.. Everything builds, but running the service doesn't seem to be working.
https://raw.githubusercontent.com/Bhlowe/owt-server/master/Dockerfile

```
wget https://raw.githubusercontent.com/Bhlowe/owt-server/master/Dockerfile
docker build -t owt .
docker run -it owt
```

This drops into bash. From there I can run:
./bin/init-all.sh --deps
./bin/start-all.sh

Now i'm just seeing the same kind of error in both init-all and start-all that looks like:

```
starting management-console, stdout -> /opt/owt-server/dist/logs/management-console.stdout
Start management-console HTTP server
starting app, stdout -> /opt/owt-server/dist/logs/app.stdout
module.js:549
    throw err;
    ^
Error: Cannot find module '/opt/owt-server/dist/extras/basic_example/samplertcservice.js'
```

**Comment by laowangnj** [comment]
The directory has been changed. see args "--sample-path ${webrtc-javascript-sdk-sample-conference-dist}", Is there any "samplertcservice.js" under ${webrtc-javascript-sdk-sample-conference-dist}?

**Comment by jimmy-huang** [comment]
@Bhlowe The mongodb service needs to be started, so before you run init-all.sh, try run:
$ service mongodb start

that seems to fix my issue inside docker, i agree that the samplertservice.js path needs to be updated, i had to patch mine from extras/basic_example/ to extras/basic_example/samples/conference

**Comment by Bhlowe** [comment]
I gave up trying. I think it’s best to have a way for developers to try out projects without spending hours fiddling with build requirements, applying patches, installing myriad prerequisites, and pulling their hair out. Docker is a great way to get a baseline build. Another way is to have binary releases. Another is to have a https demo running somewhere.

**Comment by starwarfan** [comment]
@Bhlowe It seems that the patches are not applied according to the build error. Current source needs configuring the git username and git email before running install deps.

**Comment by jimmy-huang** [comment]
@Bhlowe here's the Dockerfile i am using to build:

https://github.com/jimmy-huang/owt-server/blob/docker/docker/Dockerfile

Then once you are inside the image
# service mongodb start
# ./bin/init-all.sh 
# ./bin/start-all.sh

**Comment by tianjunwork** [comment]
Hi, @jimmy-huang, Since OWT is part of OVC, do you want to submit a PR to this project?
https://github.com/OpenVisualCloud/Dockerfiles
This project holds the dockerfile for all the deliveries of Intel visual cloud.

**Comment by jimmy-huang** [comment]
@tianjunwork I've submitted a PR here #101, you are saying it should go to that repository?

**Comment by tianjunwork** [comment]
Hi @jimmy-huang, if you could also contribute to OpenVisualCloud/Dockerfiles, that would be great. Since that project holds all the OVC components all together.

**Comment by lzhai** [comment]
Echo @tianjunwork. We can firstly add it to OWT repo. And @qwu16 can help create the OVC version according to OVC repo structure.
