### ISSUE TITLE
录制forward流， 分辨率问题

### ISSUE THREAD

**Issue by 516131179** [open-webrtc-toolkit/owt-server#171]
chrome 推送1280x720的视频， 录制没有指定分辨率， 录制出的视频分辨率有时是640x360，有时是320x180，  而Android 推送1280x720的视频，录制出来就是1280x720的视频

推流信息：
`{
    "id": "143485845242848690",
    "type": "forward",
    "media": {
        "audio": {
            "status": "active",
            "format": {
                "codec": "opus",
                "sampleRate": 48000,
                "channelNum": 2
            },
            "source": "mic",
            "optional": {
                "format": [
                    {
                        "codec": "isac",
                        "sampleRate": 16000
                    },
                    {
                        "codec": "isac",
                        "sampleRate": 32000
                    },
                    {
                        "codec": "g722",
                        "sampleRate": 16000,
                        "channelNum": 1
                    },
                    {
                        "codec": "pcma"
                    },
                    {
                        "codec": "pcmu"
                    },
                    {
                        "codec": "aac",
                        "sampleRate": 48000,
                        "channelNum": 2
                    },
                    {
                        "codec": "ac3"
                    },
                    {
                        "codec": "nellymoser"
                    },
                    {
                        "codec": "ilbc"
                    }
                ]
            }
        },
        "video": {
            "status": "active",
            "format": {
                "codec": "h264",
                "profile": "CB"
            },
            "source": "camera",
            "parameters": {
                "resolution": {
                    "width": 1280,
                    "height": 720
                },
                "framerate": 15
            },
            "optional": {
                "format": [
                    {
                        "codec": "vp8"
                    },
                    {
                        "codec": "vp9"
                    }
                ],
                "parameters": {
                    "resolution": [
                        {
                            "width": 960,
                            "height": 540
                        },
                        {
                            "width": 852,
                            "height": 480
                        },
                        {
                            "width": 640,
                            "height": 360
                        },
                        {
                            "width": 426,
                            "height": 240
                        },
                        {
                            "width": 320,
                            "height": 180
                        },
                        {
                            "width": 800,
                            "height": 600
                        },
                        {
                            "width": 640,
                            "height": 480
                        },
                        {
                            "width": 352,
                            "height": 288
                        }
                    ],
                    "framerate": [
                        6,
                        12
                    ],
                    "bitrate": [
                        "x0.8",
                        "x0.6",
                        "x0.4",
                        "x0.2"
                    ],
                    "keyFrameInterval": [
                        100,
                        30,
                        5,
                        2,
                        1
                    ]
                }
            }
        }
    },
    "info": {
        "type": "webrtc",
        "owner": "8WlDsdQvGd0k69GJAAra",
        "attributes": {
            "streamName": "main",
            "userid": "2hrvAnc8iFI27rKj",
            "role": "presenter",
            "name": "wwww",
            "video": "true",
            "audio": "true"
        },
        "inViews": []
    }
}`

是不是chrome 没办法推1280x720？

chrome：
![image](https://user-images.githubusercontent.com/31730422/59425005-a3785b80-8e07-11e9-94c8-01468fc26578.png)

当我的chrome监控如下：
![image](https://user-images.githubusercontent.com/31730422/59425995-a411f180-8e09-11e9-8e5a-33decfb73c07.png)

而录制结果：
![image](https://user-images.githubusercontent.com/31730422/59426027-b55afe00-8e09-11e9-8bf9-9265a6e49eb3.png)

**Comment by starwarfan** [comment]
Hi,
1. If resolution is specified when recording, transcoder is used and resolution is fixed.
2. If resolution is not specified, forward stream's resolution may change due to network conditions.
3. Please check the video-constraints on getUserMedia tab on chrome://webrtc-internal

**Comment by 516131179** [comment]
我调大了视频码率：

![image](https://user-images.githubusercontent.com/31730422/59479311-242e6a80-8e8f-11e9-9a79-98b06996b73a.png)


video constraints: 
{advanced: [{deviceId: {exact: ["0e4e06d203d73853bd5c781187c5b9cd8e47da75e154e2108593afb9446cb163"]}}, {width: {min: 1280}}, {width: {max: 1280}}, {height: {min: 720}}, {height: {max: 720}}]}

restapi获取流信息：
`"id":"269465784323358340","type":"forward","media":{"audio":{"status":"active","format":{"codec":"opus","sampleRate":48000,"channelNum":2},"source":"mic","optional":{"format":[{"codec":"isac","sampleRate":16000},{"codec":"isac","sampleRate":32000},{"codec":"g722","sampleRate":16000,"channelNum":1},{"codec":"pcma"},{"codec":"pcmu"},{"codec":"aac","sampleRate":48000,"channelNum":2},{"codec":"ac3"},{"codec":"nellymoser"},{"codec":"ilbc"}]}},"video":{"status":"active","format":{"codec":"h264","profile":"CB"},"source":"camera","parameters":{"resolution":{"width":640,"height":360},"framerate":15},"optional":{"format":[{"codec":"vp8"},{"codec":"vp9"}],"parameters":{"resolution":[{"width":480,"height":270},{"width":426,"height":240},{"width":320,"height":180},{"width":212,"height":120},{"width":160,"height":90},{"width":352,"height":288}],"framerate":[6,12],"bitrate":["x0.8","x0.6","x0.4","x0.2"],"keyFrameInterval":[100,30,5,2,1]}}}},"info":{"type":"webrtc","owner":"l1qzxqmxkMPn79eoAAv8","attributes":{"streamName":"main","userid":"zOIPMmh4gY65ARdp","role":"presenter","name":"虚夜鸢","video":"true","audio":"true"},"inViews":[]}}`
录制时没有指定分辨率参数。
录制视频结果还是不对：
![image](https://user-images.githubusercontent.com/31730422/59479445-a159df80-8e8f-11e9-8706-61bf4d3a0ef8.png)

**Comment by starwarfan** [comment]
Hi,
I've checked this myself, recording 720p forward stream, the resolution is consistently 720p after startup.
Some stat from my chrome://webrtc-internals
1. googFrameWidthInput: 1280
2. googFrameHeightInput: 720
3. googFrameWidthSent: 1280
4. googFrameHeightSent: 720
I see your WidthInput & HeightInput are not 720p, please check.

**Comment by 516131179** [comment]
你好能发下您创建流的参数嘛，谢谢！

**Comment by starwarfan** [comment]
width:1280, height:720

**Comment by xiandeatintel** [comment]
It is not an issue and confirmed by @starwarfan
