### ISSUE TITLE
server connection failed: Error: Joining room failed

### ISSUE THREAD

**Issue by Luosh** [open-webrtc-toolkit/owt-server#194]
hi all
   在ubuntu 16.04上安装owt, 步骤参考 [OWT Server 快速入门](https://blog.piasy.com/2019/04/14/OWT-Server-Quick-Start/index.html), 但是无法正常运行

chrome 错误提示server connection failed: Error: Joining room failed.  
logs/conference-*log, 
错误提示:ERROR: RoomController - Init media processor failed.: Timeout to make rpc to video-f752e1932aa5cb033215@192.168.5.242_0.init.
logs/viideo-agent.stdout 错误提示:NodeManager - Node video-f752e1932aa5cb033215@192.168.5.242_0 is closed on unexpected code: null

看node 中 video-agent 的进程也是伴随着 浏览器的刷新访问, 一直崩溃重启. 

重装过了几次,现象依旧, 求大神指点, 谢谢!

**Comment by Luosh** [comment]
崩溃的地方已找到, VideoMixer.cpp:66     ELOG_INFO("Init maxInput(%u), rootSize(%u, %u), bgColor(%u, %u, %u)", m_maxInputCount, rootSize.width, rootSize.height, bgColor.y, bgColor.cb, bgColor.cr); 这句log打印崩溃了, 目前注释掉能正常使用.

**Comment by Luosh** [comment]
根本原因在于, 电脑上g++ 版本使用的是4.7, 而log4cxx.so 是使用g++ 7.0+ 编译生成的,  两个版本不一致,导致log4中部分函数是无法找到的, symbol规则不一致.

**Comment by beijing-penguin** [comment]
> 根本原因在于, 电脑上g++ 版本使用的是4.7, 而log4cxx.so 是使用g++ 7.0+ 编译生成的, 两个版本不一致,导致log4中部分函数是无法找到的, symbol规则不一致.

我也遇到了类似的问题，请问 是应该升级本机g++版本到7.0吗？还是？怎么解决呢？

**Comment by Luosh** [comment]
@beijing-penguin 最后用docker编译的， 保证环境一直， 必须要在ubuntu 18.04上运行

**Comment by beijing-penguin** [comment]
> @beijing-penguin 最后用docker编译的， 保证环境一直， 必须要在ubuntu 18.04上运行

@Luosh 呃呃，是的。。环境要求挺高的。我这边早已经安装好了。
