### ISSUE TITLE
build error by mfxdefs.h

### ISSUE THREAD

**Issue by xjsXjtu** [open-webrtc-toolkit/owt-server#20]
When I build native moduls: scripts/build.js -t all --check,
 I get the following error:
fatal error: mfxdefs.h: No such file or directory

mfxdefs.h is a header file from Intel Media SDK, so it seems like I need download the Media SDK manually, or did I miss any steps?

**Comment by starwarfan** [comment]
If you use the "-t all" flag, then msdk version will be built, use the "-t mcu" if you don't want to.
If you want to use the msdk, then you need to download the Media SDK manually.

**Comment by xjsXjtu** [comment]
No problem. Which directory should I put the msdk? 

BTW, maybe it's better to write this info to the README.md, right?

Thanks a lot.

**Comment by daijh** [comment]
@xjsXjtu 
    MediaSDK is optional for build. If you do not install MediaSDK, you can simply build without MediaSDK, by "scripts/build.js -t mcu --check". And this pure software owt-server has most features for trial.
    We will optimize the documents about MediaSDK build in coming release.

**Comment by starnightcyber** [comment]
> @xjsXjtu
> MediaSDK is optional for build. If you do not install MediaSDK, you can simply build without MediaSDK, by "scripts/build.js -t mcu --check". And this pure software owt-server has most features for trial.
> We will optimize the documents about MediaSDK build in coming release.

helo, i met the same error when use "scripts/build.js -t all --check", 
so i tried to use what you say, "scripts/build.js -t mcu --check",  
and following error occurs to me:
`Finish addon - quicIO
* Checking modules...
Local network address:  IPv4=ens3:66.42.82.104 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aucodec: opus/48000/2
vidcodec: H264
vidcodec: H264
vidcodec: H264
vidcodec: H264
vidcodec: VP8
sipua is ready.
[PASS] avstream.node
[FAIL] quicIO.node Error: **librawquic.so: cannot open shared object file: No such file or directory**
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /root/owt-server/scripts/module_test.js:34:11
    at Array.map (<anonymous>)
    at /root/owt-server/scripts/module_test.js:32:10
    at ChildProcess.exithandler (child_process.js:267:7)
[PASS] mediaFrameMulticaster.node
[PASS] logger.node
[PASS] internalIO.node
[PASS] webrtc.node
[PASS] videoTranscoder-sw.node
[PASS] videoAnalyzer-sw.node
[PASS] videoMixer-sw.node
[PASS] audioMixer.node
[PASS] sipIn.node
`

**Comment by starnightcyber** [comment]
and this librawquic.so exists ...
root@vultr:~/owt-server# find / -name librawquic.so
/root/owt-server/third_party/quic-lib/dist/lib/librawquic.so

**Comment by starnightcyber** [comment]
same error when i reinstall and use "scripts/build.js -t mcu --check"
[FAIL] quicIO.node Error: librawquic.so: cannot open shared object file: No such file or directory
