### ISSUE TITLE
Issue running with docker

### ISSUE THREAD

**Issue by alexfdezsauco** [open-webrtc-toolkit/owt-server#209]
I'm trying to run the conference sample with docker but after run this:

        ./scripts/build.js -t all --check
        ./scripts/pack.js -t all --install-module --sample-path /owt-client-javascript/dist/samples/conference .
        cd dist
        ./bin/init-all.sh --deps
        ./bin/start-all.sh

and navigate to https://localhost:3004 I got this:

![image](https://user-images.githubusercontent.com/1785664/62394743-19618f00-b53c-11e9-9121-ef66816acfc3.png)

Notice the request to a wrong ip address. Actually such ip address is the ip of the container network adapter but it's  wrong use such address for the request 

	root@5e5b9f380a29:/owt-server/dist# ip addr
	1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
	    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
	    inet 127.0.0.1/8 scope host lo
	       valid_lft forever preferred_lft forever
	2: tunl0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1
	    link/ipip 0.0.0.0 brd 0.0.0.0
	3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1
	    link/tunnel6 :: brd ::
	33: eth0@if34: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
	    link/ether 02:42:ac:11:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0
	    inet 172.17.0.4/16 brd 172.17.255.255 scope global eth0
	       valid_lft forever preferred_lft forever

Any idea?

**Comment by starwarfan** [comment]
Hi, you can configure the ip address in portal/portal.toml
ip_address = "your wanted ip"

**Comment by xiandeatintel** [comment]
Hi @alexfdezsauco, @starwarfan 's answer should have helped resolve this issue, so we will close it.
