### ISSUE TITLE
mcu remote stream video was bad when client side publish a localstream

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-server#217]
1: android  device join room
2: android  device publish local stream with  vp8
3: android subscribe mixstream with vp8

result:
1: android published stream in mcu video was bad
2: android subscribe mixstream can not show video
3: ios side also found this issue 
4: all video codec found this issue

version:
mcu : Release-v20190808

**Comment by starwarfan** [comment]
#218
