### ISSUE TITLE
Is it possible to record video conference?

### ISSUE THREAD

**Issue by kooler** [open-webrtc-toolkit/owt-server#220]
Hi. Does OWT support video conference recording?

**Comment by zhouhuirun2015** [comment]
yes, see the official document

**Comment by xiandeatintel** [comment]
@kooler Yes, please take a look at https://github.com/open-webrtc-toolkit/owt-server/blob/master/doc/servermd/RESTAPI.md#56-recordings-restapisection5_6

**Comment by kooler** [comment]
Thanks @xiandeatintel! Would the recording be the composite of all video streams (placed next to each other) or it will produce separate video file for each participant?

If composite it used, is it possible to change the layout? For example to have one video large and other smaller in the corner.
