### ISSUE TITLE
wrtc.removeRemoteCandidate is not a function

### ISSUE THREAD

**Issue by zhouhuirun2015** [open-webrtc-toolkit/owt-server#225]
Compile the master branch, after join room plus few minutes later, the client is blank. And webrtc_agent log warning:wrtc.removeRemoteCandidate is not a function

**Comment by zhouhuirun2015** [comment]
this func is added after patch, but it seems not EXPORTED and symbol cannot resolved.

**Comment by xiandeatintel** [comment]
Fixed by https://github.com/open-webrtc-toolkit/owt-server/pull/224
