### ISSUE TITLE
Subscribe some simulcast stream with codec settings and resolution settings failed. 

### ISSUE THREAD

**Issue by yanbin7** [open-webrtc-toolkit/owt-server#232]
Steps
1. Publish simulcast stream using Chrome browser, resolution is 720p
publish option is

2. Try to subscribe the second and the third simulcast stream(resolution is 1280x720 and 640x360) with subscription option is
{audio: {…}, video: {…}}
audio: {codecs: Array(1)}
video:
bitrateMultiplier: undefined
codecs: Array(1)
0: {name: "vp8"}
length: 1
__proto__: Array(0)
frameRate: undefined
keyFrameInterval: undefined
resolution: {width: 640, height: 360}
rid: NaN
__proto__: Object
__proto__: Object

Subscribe action will be failed. It reports:
script2.js:2135 Uncaught (in promise) Target video stream does NOT satisfy:Resolution is not acceptable

**Comment by starwarfan** [comment]
server side bug
