### ISSUE TITLE
Encrypted and packaged mcu cannot be used

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#240]
1,Environment and platform：
43mcu，ubuntu，software，chrome77
2,Reproduce step
1,./scripts/pack.js -wf --archive v$arcname$encrypt --$encrypt -f --sample-path $samplepath
2,Encrypted and packaged mcu cannot be used
3,Result analysis
Encrypted and packaged mcu cannot be used

**Comment by cisco66666** [comment]
./scripts/pack.js -wf --archive v$arcname$encrypt --$encrypt -f --sample-path $samplepath

**Comment by yanbin7** [comment]
The bug has been fixed at latest code .  Close the issue.
