### ISSUE TITLE
Android remote stream video and audio can not recovery after wifi ->4G 

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-server#243]
android device network is wifi
1: android join room
2: android publish local stream 
3: android subscribe self forward stream
4: android close wifi and wait 5s open 4G

expect : forward stream video and audio will recovery
actual:  forward stream video and audio was bad

**Comment by zhouhuirun2015** [comment]
You can set your connection log level to DEBUG and list your conference agent log here.

**Comment by starwarfan** [comment]
#242
