### ISSUE TITLE
intel msdk cannot be enabled

### ISSUE THREAD

**Issue by zhouhuirun2015** [open-webrtc-toolkit/owt-server#246]
It crashed everytime when set hardware accelerate enabled on PC client.

**Comment by xiandeatintel** [comment]
@zhouhuirun2015 Do you mean HW acceleration doesn't work on server or client?

**Comment by zhouhuirun2015** [comment]
not work on PC client.

**Comment by zhouhuirun2015** [comment]
owt::base::GlobalConfiguration::SetVideoHardwareAccelerationEnabled(true);

**Comment by xiandeatintel** [comment]
So you would better report it on native-sdk repo here: https://github.com/open-webrtc-toolkit/owt-client-native/issues
@zhouhuirun2015
