### ISSUE TITLE
RegionUpdate not working

### ISSUE THREAD

**Issue by zhouhuirun2015** [open-webrtc-toolkit/owt-server#247]
As the document list:
[https://software.intel.com/sites/products/documentation/webrtc/restapi/index.html#RESTAPIsection5_3_3](url)
object(RegionUpdate):
    op: "replace",
    path: "/info/layout/${regionIndex}/stream",    // ${regionIndex} is an integer represents the index of the region
    value: string(streamID)                        // the new streamID for the region
}

When I make http request to update region, the server returns OK, but no layout or region changed.

url is: PATCH ${host}/v1/rooms/{roomId}/streams/ xxxxxx-common
path is: /info/layout/0~3/stream
value is my own localstream id
layout is:
![image](https://user-images.githubusercontent.com/15274287/64340609-254bdf80-d019-11e9-924e-f24f5551b815.png)

// Video layout for the case of 1 input or 6 inputs
[
  {
    "region": [
      {
        "id": "1",
        "shape": "rectangle",
        "area": {
            "left": "0",
            "top": "0",
            "width": "1",
            "height": "1"
        }
      }
    ]
  },
  {
    "region": [
      {
        "id": "1",
        "shape": "rectangle",
        "area": {
            "left": "0",
            "top": "0",
            "width": "2/3",
            "height": "2/3"
        }
      },
      {
        "id": "2",
        "shape": "rectangle",
        "area": {
            "left": "2/3",
            "top": "0",
            "width": "1/3",
            "height": "1/3"
        }
      },
      {
        "id": "3",
        "shape": "rectangle",
        "area": {
            "left": "2/3",
            "top": "1/3",
            "width": "1/3",
            "height": "1/3"
        }
      },
      {
        "id": "4",
        "shape": "rectangle",
        "area": {
            "left": "2/3",
            "top": "2/3",
            "width": "1/3",
            "height": "1/3"
        }
      },
      {
        "id": "5",
        "shape": "rectangle",
        "area": {
            "left": "1/3",
            "top": "2/3",
            "width": "1/3",
            "height": "1/3"
        }
      },
      {
        "id": "6",
        "shape": "rectangle",
        "area": {
            "left": "0",
            "top": "2/3",
            "width": "1/3",
            "height": "1/3"
        }
      }
    ]
  }
]

**Comment by starwarfan** [comment]
1. Please use remote stream ID
2. Make sure the config item "keepActiveInputPrimary" set to false (default)

**Comment by zhouhuirun2015** [comment]
11:02:03.834: start to meetingRegionUpdate, index is:1, stream id is:MediaStream-bee5d69b-e094-4133-99b5-bc9ab1082114
11:02:03.872: end to meetingRegionUpdate, index is:1, stream id is:MediaStream-bee5d69b-e094-4133-99b5-bc9ab1082114, status message: OK

the status returns OK, but it still notwork.

**Comment by zhouhuirun2015** [comment]
11:48:57.354: start to meetingRegionUpdate, index is:2, stream id is:41422984709243100
11:48:57.395: end to meetingRegionUpdate, index is:2, stream id is:41422984709243100, status message: OK

the server returns OK and it still don't work :)

**Comment by starwarfan** [comment]
If you have only two streams in mixer, then there're two active regions (first 2 of the layout setting).
You cannot set a stream to a inactive region index 2-5.
If you still have problem, please describe the case in more details.

**Comment by zhouhuirun2015** [comment]
Much appreciate for your help,
but as your described:
client A join room and publish stream.
client B join room, publish stream and set client A stream region index to 1.
not working.

**Comment by starwarfan** [comment]
In our environment, this case works well.

**Comment by zhouhuirun2015** [comment]
the server still response OK, I'll tests it in next days.

Thanks.
