### ISSUE TITLE
Error 'options.audio/video is inconsistent' when I publish screen stream!

### ISSUE THREAD

**Issue by fh345392977** [open-webrtc-toolkit/owt-server#249]
Show my code first

```javascript
navigator.mediaDevices.getDisplayMedia()
.then(stream => {
  const publishStream = new Owt.Base.LocalStream(
    stream, {video: Owt.Base.VideoSourceInfo.SCREENCAST}
  );
  this.conference.publish(publishStream).then(publication => {});
}, err => {
  Log.danger('Failed to create MediaStream');
  console.error(err);
});
```

An error like this:
![image](https://user-images.githubusercontent.com/16329330/64425639-dff1e580-d0de-11e9-8d4f-0b50e5bcf7c1.png)

I'm so confused with sharing screen! I only set video stream, why audio/video is inconsistent?

What config should I set?

Better to post some demo code, please!!

**Comment by starwarfan** [comment]
What version do you use? 
// audioConstraintsForScreen
audioConstraints = new Owt.Base.AudioTrackConstraints(Owt.Base.AudioSourceInfo.SCREENCAST);
 // videoConstraintsForScreen
 videoConstraints = new Owt.Base.VideoTrackConstraints(Owt.Base.VideoSourceInfo.SCREENCAST);
Owt.Base.MediaStreamFactory.createMediaStream(new Owt.Base.StreamConstraints(
     audioConstraints, videoConstraints)).then(stream => {
     mediaStream = stream;
     localStream = new Owt.Base.LocalStream(
          mediaStream, new Owt.Base.StreamSourceInfo(
          'screen-cast', 'screen-cast'));
     $('.local video').get(0).srcObject = stream;
     conference.publish(localStream).then(publication => {

**Comment by fh345392977** [comment]
@starwarfan 
OWT: 4.2.1
Chrome: 76

**Comment by starwarfan** [comment]
Have you tried above sample code?

**Comment by fh345392977** [comment]
Yes I tried.
![image](https://user-images.githubusercontent.com/16329330/64598811-f358c580-d3ea-11e9-9118-16e8635f56ee.png)
But it's the same error.

**Comment by starwarfan** [comment]
You can call getTracks on mediaStream once you created to see whether it's consistent with your publish options

**Comment by fh345392977** [comment]
Thank you, I found the problem. When I share the screen, there only a video track.

But 'StreamConstraints' needs an audio source.

How can I create a MediaStream without video?

**Comment by fh345392977** [comment]
I find something new again.

When I choose to share Chrome Tab, it has a 'share audio' checkbox, so it works.

But I can't share application window, like a PPT, a Word or something else.

**Comment by starwarfan** [comment]
You can set { audio: false } when publish a video-only stream

**Comment by fh345392977** [comment]
Yeah, it works. Thank you very much!!
