### ISSUE TITLE
Jitsi call mcusip failed

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#250]
Jitsi call mcusip failed

log
new participant joined: t {id: "SipIn980862716314", addEventListener: ƒ, removeEventListener: ƒ, clearEventListener: ƒ, dispatchEvent: ƒ, …}
new stream added 201345397955717380
script2.js:1473 subscribe 201345397955717380 failed: Target video stream does NOT satisfy:Requested video stream
participant SipIn980862716314 left
script2.js:1604 remote stream 201345397955717380 is ended
script2.js:1494 mix stream 201345397955717380 to common failed:  Internal Server Error

**Comment by xiandeatintel** [comment]
Fixed by #245
