### ISSUE TITLE
mcusip

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#251]

**Comment by cisco66666** [comment]
Mcusip call jitsi failed         9--5  mcu
call rest api  createsipcalls failed

log
new stream added 178660431856114700
owt.js:9 ICE connection state changed to checking
2owt.js:9 Remote stream added.
owt.js:9 Empty candidate.
owt.js:9 ICE connection state changed to connected
script2.js:1473 subscribe 178660431856114700 failed: Error: Source stream loss
script2.js:1636 participant SipOut28303445117 left
script2.js:1604 remote stream 178660431856114700 is ended

**Comment by xiandeatintel** [comment]
Fixed by #245
