### ISSUE TITLE
LayoutUpdate not working

### ISSUE THREAD

**Issue by zhouhuirun2015** [open-webrtc-toolkit/owt-server#255]
PATCH /rooms/5d70d9fe78df8847b9110255/streams/5d70d9fe78df8847b9110255-common HTTP/1.1

{"op":"replace","path":"/info/layout","value":"[{\"region\":{\"area\":\"{\\\"height\\\":\\\"1\\\",\\\"left\\\":\\\"0\\\",\\\"top\\\":\\\"0\\\",\\\"width\\\":\\\"1\\\"}\",\"id\":\"primary\",\"shape\":\"rectangle\"},\"stream\":\"383274715088635800\"}]"}

call layout update func on conference publish cb func

The server didn't response anything.

**Comment by cisco66666** [comment]
[{"op":"replace","path":"/info/layout","value":"[{"region":{"area":"{\"height\":\"1\",\"left\":\"0\",\"top\":\"0\",\"width\":\"1\"}","id":"primary","shape":"rectangle"},"stream":"383274715088635800"}]"}]

**Comment by starwarfan** [comment]
We cannot reproduce this issue

**Comment by zhouhuirun2015** [comment]
> [{"op":"replace","path":"/info/layout","value":"[{"region":{"area":"{"height":"1","left":"0","top":"0","width":"1"}","id":"primary","shape":"rectangle"},"stream":"383274715088635800"}]"}]

1. add [].
2. instead of using "mix" function like code in PC client example, I wrote my own http patch code and it work.
