### ISSUE TITLE
Delete the room, what happened

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#256]
A room pub a stream, a sub mix

Delete this room, MCU log as follows:
logs/portal.stdout:2019-09-10 04:19:49.849  - ERROR: Main - Fault on conference controller(type: node id: conference-2ced6cd7becc05fc170e@10.239.61.117_0 ) of participant UclmekMlcMYKm0kCAAAA was detected, drop it.
[webrtc@webrtc51 dist]$ grep fail logs/ -ri
logs/portal.stdout:2019-09-10 04:19:51.850  - INFO: Portal - Failed in leaving,  Timeout to make rpc to conference-2ced6cd7becc05fc170e@10.239.61.117_0.leave

**Comment by xiandeatintel** [comment]
It is expected behavor. Only if all clients in the room receive "server_disconnected" event and acturally disconnect from server.
