### ISSUE TITLE
 Audio Codec Problem

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#257]
1,  A stream of pub with respect to audio codec g722 and libc    ---failed
2,  A stream of sub with respect to audio codec g722 and libc    ---failed

**Comment by cisco66666** [comment]
chrome log：
(index):1 Uncaught (in promise) DOMException: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': Failed to set remote answer sdp: Failed to set remote audio description send parameters.

**Comment by starwarfan** [comment]
#258
