### ISSUE TITLE
Meeting recording issue

### ISSUE THREAD

**Issue by xdding** [open-webrtc-toolkit/owt-server#266]
We test the recording rest api, test result indicates that this api can only record one stream, can not record mixed stream, do you have solution to fix this issue?

**Comment by xiandeatintel** [comment]
Recording should support mixed stream, please make sure your specify the source stream correctly in your test.
If it doesn't work on your side, please file another issue with the detailed JSON body of your recording request and the configuration of the room, and make sure openh264 is installed if H264 is required.
