### ISSUE TITLE
Test Suite : Simulcast/ Chrome-Chrome/-event

### ISSUE THREAD

**Issue by cisco6** [open-webrtc-toolkit/owt-server#267]
1 | Publish side set simulcast

2 | subscribe the simulcast stream with correct rid : h  and codec set as : {name:vp8}, resolution set as :320x240 etc.
 

3 | use another browser subscribe simulcast stream with correct rid :  q

4 | publish side leave the room

5 subscribe ended  --- The incident did not occur.

**Comment by cisco66666** [comment]
Verified
