### ISSUE TITLE
Layout-custom layout with 3x3-1080p

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-server#272]
steps:	
    1. Use default layout and set base mix resolution to 1080p	
    2.  9 different video resolution(2 sif,  3 vga, 2 hd720p, 2 hd1080p) stream added to mix and 
         susbcribe mix stream
results:
    there have black piexl on 2 sif and  3 vga streams left and right
expect:
    each resolution input stream fit 3x3 layout well, there is no black piexl around the video in each region

**Comment by lzhai** [comment]
Choose crop if don't want to get black background in video.

**Comment by wayunge** [comment]
mixStream picture:
![image](https://user-images.githubusercontent.com/47023511/65855024-b7cd6d80-e390-11e9-89e1-0b05b88a207d.png)
Configuration details：
![image](https://user-images.githubusercontent.com/47023511/65855085-e0edfe00-e390-11e9-9b83-980e85da80ab.png)
 still has black piexl

**Comment by starwarfan** [comment]
From the stream picture I can tell that your mix stream is not 1080p, the w/h ratio is not right.
Your configuration is not consistent with your stream picture.
Real 1080p mix stream should look like this one:
![image](https://user-images.githubusercontent.com/14191484/66447657-8e43ce80-ea81-11e9-8217-f6c1aafb025f.png)
Not yours:
![image](https://user-images.githubusercontent.com/14191484/66447673-9d2a8100-ea81-11e9-95a6-d82fd5c8c114.png)

So I doubt your test methods and results.
This scenario works well in my environments.

**Comment by cisco66666** [comment]
Verified
