### ISSUE TITLE
dash for mcu then the 'mpd' file not read

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-server#276]
os : ubuntu 18.04
Release version : Release-v20190923ubuntu.tgz
chromeVersion : 77
steps:
   1、**post url** : /rooms/5d6dc4ec196e9930943507bb/streaming-outs
         **send data** : {"media":{"audio":{"from":"342588405410930940","format":{"codec":"aac","channelNum":2,"sampleRate":48000}},"video":{"from":"342588405410930940","format":{"codec":"h264","profile":"CB"}}},"url":"/var/www/html/mcu.mpd"}
      **return data** : {"id":"251754501105858180","media":{"audio":{"from":"342588405410930940","format":{"codec":"aac","channelNum":2,"sampleRate":48000},"status":"active"},"video":{"from":"342588405410930940","format":{"codec":"h264","profile":"CB"},"status":"active"}},"url":"/var/www/html/mcu.mpd"}
  2、centos install apacher server
  3、create file "dash.html" in "/var/www/html/mcu.mpd" : 
            ###  <script src="https://cdn.dashjs.org/latest/dash.all.min.js"></script>
           ###<video data-dashjs-player autoplay controls src="mcu.mpd" 
           ###type="application/dash+xml"></video     >
  4、use chrome resquest "http://apacherIp/dash.html

**Expected results：**
    the dash.html video work welll
**Actual result：**
     the dash.html not video

**Comment by cisco66666** [comment]
Has verified that jianhui has already seen it, waiting for further information

**Comment by GaoMingKai** [comment]
File permissions cause a failure, function is normal after adding file permissions
