### ISSUE TITLE
dropParticipant haven't trigger 'ended' event

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-server#288]
Operational steps:
    1. A call createToken to get valid token,A join room.
    2. B join room and pulish a atream.
    3. A pulish a atream then subscribe B's forward stream
    4. B subscribe A's forward stream.
    5. After A  call dropParticipant event
Actual results:
      A haven't trigger A's subscribtion ended event and  publication ended event and remoteStream ended event. B haven't trigger A's subscribtion ended event 

Expect:
     A need to trigger A's subscribtion ended event and  publication ended event and remoteStream ended event. B need to trigger A's subscribtion ended event

**Comment by starwarfan** [comment]
remoteStream ended won't be triggered

**Comment by wayunge** [comment]
verified.
mcu: Release-v20191020encrypt.tgz
browser: chrome 77.0.3865.120
