### ISSUE TITLE
Recorded mix stream's video codec is different from setting video codec

### ISSUE THREAD

**Issue by wayunge** [open-webrtc-toolkit/owt-server#293]
environment:
sysytem: ubuntu software and centos software
any browser
mcu: Newest

step:

1.user join room,and publish a stream
2.user subscribe a mix stream
3.record a mix stream with set video codec to 'h264-B'
4.use ffprobe to check recorded file profile align with setting value
result:
Video: h264 (Constrained Baseline)
expect:
Recorded mix stream's video codec should be the starting set video codec
additional:
Recorded mix stream's video codec is  the starting set video codec on hardware

**Comment by starwarfan** [comment]
Expected behaviour

**Comment by starwarfan** [comment]
openh264 constrained-baseline behaivour

**Comment by wayunge** [comment]
verified.
