### ISSUE TITLE
rtmp streamout error

### ISSUE THREAD

**Issue by QtyearLin** [open-webrtc-toolkit/owt-server#30]
I try rtmp with the MCU server,but failed, 

POST /rooms/5c6a239bfe81c28b25c634a4/streaming-outs
body: {"media":{"audio":{"from":"5c6a239bfe81c28b25c634a4-common"},"video":{"from":"5c6a239bfe81c28b25c634a4-common"}},"url":"rtmp://192.168.1.118:1935/live/1"}

then received  HTTP/1.1 500 Internal Server Error

How do I solve the problem?

**Comment by daijh** [comment]
@QtyearLin 
&ensp;&ensp;&ensp;&ensp;Do you install the dependencies as described in section "2.3.5 Compile and deploy ffmpeg with libfdk_aac"?

https://github.com/open-webrtc-toolkit/owt-server/blob/master/doc/servermd/Server.md

&ensp;&ensp;&ensp;&ensp;Please also check error message in owt-server/logs/streaming-xxx@xxx_x.log

**Comment by xiandeatintel** [comment]
As advised by @daijh , need to double check the installation of libfdk_aac.
