### ISSUE TITLE
 error: ‘RTCPHeader’ does not name a type

### ISSUE THREAD

**Issue by chenxiemin** [open-webrtc-toolkit/owt-server#304]
OS: ubuntu 18
Version: 4.2.x
Error:
../../../../core/owt_base/WebRTCTransport.h: In member function ‘virtual bool owt_base::WebRTCTransport<dataType>::SendRtcp(const uint8_t*, size_t)’:
../../../../core/owt_base/WebRTCTransport.h:57:11: error: ‘RTCPHeader’ does not name a type
     const RTCPHeader* chead = reinterpret_cast<const RTCPHeader*>(data);

Step:
./scripts/installDepsUnattended.sh
./scripts/build.js -t all --check

**Comment by chenxiemin** [comment]
My env issue.

**Comment by CharleyWangZJU** [comment]
how to fix this issue?

**Comment by chenxiemin** [comment]
I use a clean installed Ubuntu 18.04 to fix it.

**Comment by laplaceliu** [comment]
I encounter this problem too.
That changing file `source/agent/webrtc/webrtcLib/binding.gyp` can fix this issue.
You can just move `'erizo/src/erizo/rtp',`, put it after `'../../../core/common',`.
After that, the `binding.jyp` will looks like:
```
    'include_dirs': [
      "<!(node -e \"require('nan')\")",
      'conn_handler',
      'erizo/src/erizo',
      'erizo/src/erizo/lib',
      'erizo/src/erizo/dtls',
      'erizo/src/erizo/pipeline',
      'erizo/src/erizo/thread',
      'erizo/src/erizo/stats',
      '../../../core/common',
      'erizo/src/erizo/rtp',
      '../../../core/owt_base',
      '../../../core/rtc_adapter',
      '../../../../third_party/webrtc/src',
      '../../../../build/libdeps/build/include',
      '<!@(pkg-config glib-2.0 --cflags-only-I | sed s/-I//g)',
    ],
```
