### ISSUE TITLE
Only support single video codec settings for simulcast stream 

### ISSUE THREAD

**Issue by yanbin7** [open-webrtc-toolkit/owt-server#306]
Using Chrome browser for this testing .
Chrome browser version 
Version 76.0.3809.132 (Official Build) (64-bit)
Steps
1. set publish options for simulcast stream
        publishOptions = {
        audio : true,
        video:[
                            {codecPayloadType:125,rid: 'q', active: true, scaleResolutionDownBy: 4.0},
                            {codecPayloadType:125,rid: 'h', active: true, scaleResolutionDownBy: 2.0},
                            {codecPayloadType:125,rid: 'f', active: true}
                          ]
    }

2. publish camera stream with this option and codec settings , set codec as H264 
client.publish(localStream, publishOptions,['H264'])
check remote stream codec info in settings , it is correct and is h264.

3. repeat step2 and set codec as H264, VP8 and VP9 
client.publish(localStream, publishOptions,['H264','VP8','VP9'])
check remote stream codec info in settings , it is incorrect and is vp8.
video: Array(3)
0: e
bitrate: NaN
codec: e {name: "vp8", profile: undefined}
frameRate: 60
keyFrameInterval: undefined
resolution: e {width: 320, height: 180}
rid: undefined

**Comment by lzhai** [comment]
MCU should choose the first order codec specified by client which MCU can support

**Comment by yanbin7** [comment]
Verified.  The bug has been fixed at latest code.
