### ISSUE TITLE
Instructions for setup on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by iveusss** [open-webrtc-toolkit/owt-server#312]
Hi.

I have an problem compiling/installing owt-server on Ubuntu 18.04.3 LTS.

Starting from Intel Media SDK dependency not available, giving errors on video-transcoder-msdk and video-mixer-msdk. With errors - no mfx folder available, then - no lmfx.

Can someone update the docs please?

**Comment by starwarfan** [comment]
Hi,
You can build without  MSDK first to have a try. We'll update the docs later.

**Comment by starwarfan** [comment]
#313
