### ISSUE TITLE
Sorting the rid value in descending order causes the bitsReceived to be abnormally distributed.

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-server#348]
os : ubuntu 18.04
package : CS_WebRTC_Conference_Server_MCU.v4.3.Ubuntu.tgz
chromeVersion : 77
steps : 
     **publish :**
     options = {
        audio : false,
        video : [
                    {rid: 'f', active: true, scaleResolutionDownBy: 1.0},
                    {rid: 'q', active: true, scaleResolutionDownBy: 2.0},
                    {rid: 'h', active: true, scaleResolutionDownBy: 4.0},
                ]
}
**result:**
    High resolution bitsReceived are low, low resolution bitsReceived are high

**Comment by starwarfan** [comment]
For chrome, the resolution order should be:
 [
{rid: 'f', active: true, scaleResolutionDownBy: 4.0},
{rid: 'q', active: true, scaleResolutionDownBy: 2.0},
{rid: 'h', active: true, scaleResolutionDownBy: 1.0},
],
But for firefox, the order should be reversed.
We'll add this in document.

**Comment by GaoMingKai** [comment]
Verified normal
