### ISSUE TITLE
VAD: How to know the active speaker do not speak anymore?

### ISSUE THREAD

**Issue by chenxiemin** [open-webrtc-toolkit/owt-server#359]
Assume server sends "activeInput" after participant A's speaking, if other participants are all muted, how to know when A's not speaking anymore?

**Comment by chenxiemin** [comment]
Anybody help on it, thanks.

**Comment by daijh** [comment]
"activeInput" will stay at last speaker if all participants muted, until new participant becomes "active".
Currently it does not support not-speaking detection.

**Comment by chenxiemin** [comment]
Frankly speaking, I think this behavior is not user-friendly, do you have any idea to improve this or can you please point out the server side code for me if I want to try by myself? Thank you.

**Comment by daijh** [comment]
We encourage to customize to meet various different application usages.

// send notification
https://github.com/open-webrtc-toolkit/owt-server/blob/master/source/agent/audio/audioMixer/AcmmFrameMixer.cpp
void AcmmFrameMixer::VadParticipants

// calculate all participants' audio frame energy
https://github.com/open-webrtc-toolkit/owt-deps-webrtc/blob/59-server/webrtc/modules/audio_conference_mixer/source/audio_conference_mixer_impl.cc
void AudioConferenceMixerImpl::UpdateVadStatistics

**Comment by chenxiemin** [comment]
Thank you so much.
