### ISSUE TITLE
How to make streaming-ins/outs success?

### ISSUE THREAD

**Issue by fh345392977** [open-webrtc-toolkit/owt-server#369]
I need an RTMP/HLS stream in the room. But I don't know whether to use '/v1/rooms/{roomId}/streaming-outs' or '/v1/rooms/{roomId}/streaming-ins', so I try both.

`streaming-ins`
![image](https://user-images.githubusercontent.com/16329330/68454714-786a2a80-0234-11ea-95e4-9f5cddbe31ad.png)

Response
```
{"error":{"code":2001,"message":"Error Operation failed"}}
```

`streaming-outs`
![image](https://user-images.githubusercontent.com/16329330/68454908-00503480-0235-11ea-8a3e-8047bbfb7bc8.png)

Response
```
{"error":{"code":2001,"message":"Error RPC:addServerSideSubscription failed"}}
```

It seems like 'streaming-outs' is the right way. But how can I fix "Error RPC:addServerSideSubscription failed"?

The RTMP server was started by running 'nginx-rtmp' image by docker.

By the way, how to publish a HLS stream?

**Comment by daijh** [comment]
Please refer to the doc below:

https://github.com/open-webrtc-toolkit/owt-server/blob/master/doc/servermd/Server.md
2.3.5 Compile and deploy ffmpeg with libfdk_aac {#Conferencesection2_3_5}

And check ./logs/streaming-xxxxxxxx@xx.xx.xx.xx_x.log if any clues
