### ISSUE TITLE
ERROR: Command failed: [ -s not ]

### ISSUE THREAD

**Issue by linewei** [open-webrtc-toolkit/owt-server#371]
I installed in ubuntu 18.04,  Build native components successed, Pack built components and js files successed also, but lost 'bin' in dist directory.

i got a error log below when run pack.js :
ERROR: Command failed: [ -s not ]

**Comment by linewei** [comment]
Not appeared when i re-complied in new ubuntu device.

**Comment by CharleyWangZJU** [comment]
I met this issue too.

**Comment by CharleyWangZJU** [comment]
I fixed this issue in the below cmd.
export PATH="~/.nvm/versions/node/v8.15.0/bin":$PATH
