### ISSUE TITLE
创建房间时nuve模块报错-OWT-4.1（官网下载版本）

### ISSUE THREAD

**Issue by qzn928** [open-webrtc-toolkit/owt-server#38]
我们在通过接口批量创建service和room时发现两个问题：
一、创建接口延迟高；
二、创建房间时nuve模块报错；

我是在阿里云上测试的，rabbitmq部署在本机，mongo使用阿里云的mongo-v3.2，所有服务都是纯内网连接，OWT组件都在同一台设备，配置使用默认。
测试步骤：
1、init nuve生成serviceid和key；
2、api接口并行500左右的请求创建房间；
3、大概30分钟左右会出现接口超时（5S）和nuve报错的情况；
具体错误信息：
`<--- Last few GCs --->

[10094:0x2d506c0]  1597301 ms: Mark-sweep 1392.8 (1457.9) -> 1392.6 (1458.9) MB, 1695.0 / 0.0 ms  allocation failure GC in old space requested
[10094:0x2d506c0]  1598820 ms: Mark-sweep 1392.6 (1458.9) -> 1392.6 (1425.9) MB, 1518.6 / 0.0 ms  last resort GC in old space requested
[10094:0x2d506c0]  1599636 ms: Mark-sweep 1392.6 (1425.9) -> 1392.6 (1425.9) MB, 816.5 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xb6564aa5879 <JSObject>
    1: /* anonymous */ [/var/www/dream/atlas-agent/Release-v4.1/nuve/node_modules/mongoose/lib/plugins/validateBeforeSave.js:~8] [pc=0x3d51114b8998](this=0x284e7e736491 <model map = 0x3a57c310ec79>,next=0xd82daf226f1 <JSFunction fnWrapper (sfi = 0x116a26637471)>,options=0xd82daf223e9 <JSFunction (sfi = 0x116a26635b81)>)
    2: _next [/var/www/dream/atlas-agent/Release-v4.1/nuve/node_modules/hooks...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
 2: 0x8c21ec [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
 5: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
 6: v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag, v8::internal::MinimumCapacity) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
 7: v8::internal::HashTable<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::EnsureCapacity(v8::internal::Handle<v8::internal::NameDictionary>, int, v8::internal::PretenureFlag) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
 8: v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::EnsureCapacity(v8::internal::Handle<v8::internal::NameDictionary>, int) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
 9: v8::internal::BaseNameDictionary<v8::internal::NameDictionary, v8::internal::NameDictionaryShape>::Add(v8::internal::Handle<v8::internal::NameDictionary>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyDetails, int*) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
10: v8::internal::LookupIterator::ApplyTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
11: v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow, v8::internal::Object::StoreFromKeyed) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
12: v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::LanguageMode, v8::internal::Object::StoreFromKeyed) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
13: v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/var/www/dream/atlas-agent/node-v8.11.4-linux-x64/bin/node]
14: 0x3d5110f842fd
2019-03-20 18:37:07.162  - INFO: Nuve - Worker 10094 died`

**Comment by starwarfan** [comment]
Hi,
It seems that the memory used has reached the node limit.
建议在运行时查看Nuve进程的内存使用情况，如果是达到了单个node进程的限制。可以尝试在启动Node时添加“--max-old-space-size”参数设定大小，或者修改toml文件中的numberOfProcess=*来增加进程数。

**Comment by xiandeatintel** [comment]
Sorry we don't track issues of 4.1 and older versions here.
Please try it out on 4.2 or 4.2.1 ICS Server and apply the suggestions @starwarfan mentioned above. And file another issue if it is reproduced.

**Comment by qzn928** [comment]
> Hi,
> It seems that the memory used has reached the node limit.
> 建议在运行时查看Nuve进程的内存使用情况，如果是达到了单个node进程的限制。可以尝试在启动Node时添加“--max-old-space-size”参数设定大小，或者修改toml文件中的numberOfProcess=*来增加进程数。
> If the memory reaches a VM's memory limit.
> 如果是内存达到了一个机器的上限，可以尝试在多台机器部署该模块，将请求router到不同的机器上。

好的，谢谢
