### ISSUE TITLE
libnice-CRITICAL **:  file address.c: line 166 (nice_address_set_port): should not be reached

### ISSUE THREAD

**Issue by linewei** [open-webrtc-toolkit/owt-server#382]
Ubuntu 18.04 
MCU Server V4.3

use app demo , 3 streams . about 1 minute , chrome console log ' ice disconnect ... close', than get black stream from sever.
in the server side, log report  as below: 

---------

(process:19407): libnice-CRITICAL **: 14:54:24.593: file address.c: line 166 (nice_address_set_port): should not be reached
2019-11-29 14:54:25,630  - DEBUG: TimeoutChecker - Handling dtls timeout, checks left: 14
2019-11-29 14:54:26,630  - DEBUG: TimeoutChecker - Handling dtls timeout, checks left: 13
2019-11-29 14:57:05,960  - WARN: LibNiceConnection - id: 97220262413881820,  message: failed and not received all candidates, newComponentState:4
2019-11-29 14:57:22,756  - WARN: LibNiceConnection - id: 893411164681338200,  message: failed and not received all candidates, newComponentState:4
2019-11-29 14:57:22,823  - WARN: LibNiceConnection - id: 148415377248952030,  message: failed and not received all candidates, newComponentState:4
2019-11-29 14:57:29.716  - WARN: WorkingNode - Exiting on SIGTERM
~

**Comment by linewei** [comment]
It's the problem of sysctl params , use ubuntu default configure is ok.

**Comment by nareshinstavc** [comment]
is this issue get resolves with CentOS package Too?

**Comment by Alex-YddeR** [comment]
I am facing same issue on CentOS MCU even i did used default sysctl params. suddenly 1 user video gets blacked out and we are using SFU with transcoding. below are the logs

(process:22645): libnice-CRITICAL **: 05:44:28.527: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:46:35.194: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:46:35.198: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:46:35.200: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:46:35.201: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:46:36.961: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:46:36.965: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:48:52.120: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:48:52.121: file address.c: line 166 (nice_address_set_port): should not be reached
2020-09-05 05:50:15,514  - WARN: LibNiceConnection - id: 502097630477101200,  message: failed and not received all candidates, newComponentState:4

(process:22645): libnice-CRITICAL **: 05:51:25.503: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:51:25.503: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:51:25.505: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:51:25.506: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:54:14.187: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:54:14.188: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:54:14.190: file address.c: line 166 (nice_address_set_port): should not be reached

(process:22645): libnice-CRITICAL **: 05:54:14.191: file address.c: line 166 (nice_address_set_port): should not be reached
2020-09-05 05:55:58,059  - WARN: LibNiceConnection - id: 604506218712965200,  message: failed and not received all candidates, newComponentState:4
2020-09-05 05:57:02,781  - WARN: LibNiceConnection - id: 309974366218250560,  message: failed and not received all candidates, newComponentState:4

(process:22645): libnice-CRITICAL **: 05:57:20.321: file address.c: line 166 (nice_address_set_port): should not be reached

**Comment by Alex-YddeR** [comment]
This error still appears in master branch 

(process:2585): libnice-CRITICAL **: 04:14:49.669: file address.c: line 166 (nice_address_set_port): should not be reached

**Comment by starwarfan** [comment]
Hi,
Can you provide you ICE candidate format when these errors occur?
