### ISSUE TITLE
MCU server v4.3 can not work in ubuntu 18.04!

### ISSUE THREAD

**Issue by linewei** [open-webrtc-toolkit/owt-server#383]
Does somebody use v4.3 in product? let me know please! 
when i update owt server from v4.1 to v4.3 , i met critical bug about ice connect, I don't know it's my fault or it's a bug, so if you use v4.3 in product , please note here.

**Comment by CharleyWangZJU** [comment]
Everything goes well except that audio and vedio are out of sync when I used hardware.

**Comment by linewei** [comment]
It's the problem of sysctl params , use ubuntu default configure is ok.
