### ISSUE TITLE
rtmp stream out never end?

### ISSUE THREAD

**Issue by seanwong1127** [open-webrtc-toolkit/owt-server#386]
Hi,

I use "streaming-outs" api to stream video to a rtmp server,
But when every body exit the room, the rtmp stream task still working.
It tuns out to keep streaming a blank screen video.

How can I stop the stream when every client unpublished?

**Comment by daijh** [comment]
RTMP streamout will not stop automatically.
You should explicitly stop it with streaming API.

@seanwong1127 @starwarfan
