### ISSUE TITLE
How to start owt-server?

### ISSUE THREAD

**Issue by wackykid** [open-webrtc-toolkit/owt-server#414]
Sorry, brand new to owt-server. I followed the README to build owt-server for Ubuntu 18.04.

- Started with a fresh copy of Ubuntu 18.04.03 and did the following:

- ran scripts/installDepsUnattended.sh according to README
- Installed Intel MSDK and various dependencies (not inside README, but build script skipped video-mixer-msdk and video-transcoder-msdk because missing MSDK)
- Build native components: scripts/build.js -t all --check
- Pack built components and js files: scripts/pack.js -t all --install-module --sample-path ${webrtc-javascript-sdk-sample-conference-dist}

finally everything seems all good, but the quick start says:

> In the repository root, run following commands to start media server on single machine:
> 
>     ./bin/init-all.sh --deps
>     ./bin/start-all.sh
>     Open https://localhost:3004 to visit the web sample page. Due to the test certificate, you may need confirm this unsafe access.
> 

but there is no bin directory in the repository root even after going through the build instructions. what am i missing? all i see is:

> $ ls -l
> total 60
> drwxr-xr-x  3 kxr kxr  4096 Jan 23 14:35 build
> drwxr-xr-x  2 kxr kxr  4096 Jan 23 14:34 cert
> drwxr-xr-x 15 kxr kxr  4096 Jan 23 16:48 dist
> drwxr-xr-x  6 kxr kxr  4096 Jan 23 14:34 doc
> drwxr-xr-x  3 kxr kxr  4096 Jan 23 14:34 docker
> -rw-r--r--  1 kxr kxr 11358 Jan 23 14:31 LICENSE
> drwxr-xr-x  3 kxr kxr  4096 Jan 23 14:51 node_modules
> -rw-r--r--  1 kxr kxr   304 Jan 23 14:51 package-lock.json
> -rw-r--r--  1 kxr kxr  3212 Jan 23 14:34 README.md
> drwxr-xr-x  4 kxr kxr  4096 Jan 23 14:34 scripts
> drwxr-xr-x 11 kxr kxr  4096 Jan 23 14:31 source
> drwxr-xr-x  4 kxr kxr  4096 Jan 23 14:34 test
> drwxr-xr-x  8 kxr kxr  4096 Jan 23 15:00 third_party
>

**Comment by wackykid** [comment]
seems that the README is not for the Github but for the Intel® Collaboration Suite for WebRTC package downloadable from Intel's website. when I download that package, it contains the bin directory and the scripts that the README instructed to follow.

**Comment by Kmtest-rgb** [comment]
Hi
  then how do you start the server, which you just built from source.  As you mentioned there is no bin folder and related scripts.  I would like to start the owt-server which I just built from git source.  I dont want to run the pre-built version for now. 

thanks
