### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by bibitoo** [open-webrtc-toolkit/owt-server#432]
I copy the conference sample to my project and got a black screen. There is no error on client.
I have implement the rest path:
/rooms/{roomId}/streams/{streamId}
/rooms/{roomId}/streams
/tokens
When I run my project, I got a black screen.
1. Open my project, localstream OK, conference screen is black.
2. Open a new tab for https:/192.168.0.2:3004 , Local stream and conference screen are ok.
Then change to my project tab, the conference screen is ok too.
3. Close the https:/192.168.0.2:3004 tab, refresh my project, the  conference screen is black again.

appreciate for any help

**Comment by starwarfan** [comment]
Hi, after you close the https:/192.168.0.2:3004 tab, the publication will be stopped, then no streams are mixed in conference screen, so it's black. Is that correct?

**Comment by bibitoo** [comment]
@starwarfan Thanks for reply.
When I open https:/192.168.0.2:3004 tab in chromium, the conference have two streams mixed.
When I close the https:/192.168.0.2:3004 tab, the conference has one stream  display. It seems every thing is ok. If I refresh my project, I got black in conference screen.

**Comment by bibitoo** [comment]
I found the reason. My request for /rooms/{roomId}/streams/{streamId} method is get, It should be patch.
