### ISSUE TITLE
keystore error

### ISSUE THREAD

**Issue by bibitoo** [open-webrtc-toolkit/owt-server#434]
I got a certificate and chains from Let's Encrypt, make cfx file by this command line:
`openssl pkcs12 -export -out certificate.pfx -inkey privkey.pem -in cert.pem -certfile chain.pem`
with empty password.
But when I use this certificate.pfx file by change config file 
management_console/management_console.toml
to my certificate.pfx, I got an error:
`starting management-console, stdout -> /home/owt/owt-server-4.3/dist/logs/management-console.stdout
/home/owt/owt-server-4.3/dist/management_console/index.js:82
      log.warn('Failed to setup secured server:', err);
      ^

ReferenceError: log is not defined
    at cb (/home/owt/owt-server-4.3/dist/management_console/index.js:82:7)
    at ReadStream.<anonymous> (/home/owt/owt-server-4.3/dist/management_console/cipher.js:46:5)
    at emitOne (events.js:116:13)
    at ReadStream.emit (events.js:211:7)
    at fs.js:2001:12`

After modify management_console/index.js file change "log.warn" to "console.log", I can see the error message:
`starting management-console, stdout -> /home/owt/owt-server-4.3/dist/logs/management-console.stdout
Failed to setup secured server: { Error: ENOENT: no such file or directory, open '/home/owt/owt-server-4.3/dist/.owt.keystore'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/owt/owt-server-4.3/dist/.owt.keystore' }
`
My quetions is :
1. How to generate a correct certificate cfx file from Let's Encrypt ?
2. How to generate .owt.authstore and .owt.keystore file ?
3. In cipher.js , 
`  // Replace k with your key generator
  k: Buffer.from('3d84a1efc77268c98bc6ca2921eb35a6d82a40a38696d25fbb64ff1733cd2523', 'hex'),`
How to get the key?

**Comment by starwarfan** [comment]
If you replaced the certifacate.pfx, run the "initcert.js" and enter your passphrase to generate a keystore file

**Comment by bibitoo** [comment]
@starwarfan Thanks. It work.
