### ISSUE TITLE
Is there an easy way to replaceTrack after publish localstream?

### ISSUE THREAD

**Issue by bibitoo** [open-webrtc-toolkit/owt-server#458]
I want to  change microphone or share screen. How could I call sender.replaceTrack(track) after conference.publish bean called?

**Comment by starwarfan** [comment]
If you are using js, you can move this issue to https://github.com/open-webrtc-toolkit/owt-client-javascript

**Comment by bibitoo** [comment]
Yes. It's js client issue.
