### ISSUE TITLE
webrtc-agent process crash

### ISSUE THREAD

**Issue by caikunru** [open-webrtc-toolkit/owt-server#470]
When the webrtc-agent's memory grows to 1.4GB, and someone enters the conference room, the webrtc-agent will crash.

Also, when 10 people join the conference, the webrtc-agent's memory keeps growing. Is this a memory leak in the conference?

**Comment by starwarfan** [comment]
Hi, did the webrtc-agent's memeory keeps growing all the time or just a short time after the join?
If people join the conference and subscribe each other's stream, then there would be 90 streams, it may take some time to increase the memory.

**Comment by caikunru** [comment]
入会10人，内存会持续增长，测试过10人入会16个小时，内存可以增长到28GB。感觉这样非常的不合理。偶尔webrtc-agent还会崩溃。请教您这些问题可能的原因是什么？日志文件实在没办法给您看了，日志文件大概有30GB

**Comment by starwarfan** [comment]
Hi, which branch were you using? There can possibly be a memory leak in your case.

**Comment by caikunru** [comment]
分支是4.3.X。
启动多个webrtc-agent会解决这个问题吗？webrtc-agent在为某个会议室服务的时候都会启动一个webrtc-XXXXXXXXXXXXXXXXXX的新进程专门处理数据，我启动多个webrtc-agent，它也不会分担那个会议的负载啊。个人感觉好像不会改善这个问题。希望您们尽快修改这个线程模型以解决这些问题，谢谢

**Comment by starwarfan** [comment]
To start multiple webrtc-agent on single machine, you need copy the package (or only `webrtc_agent`, `bin` folder and `package.json`) somewhere else and run `bin/daemon.sh start webrtc-agent` in that place.
To use multiple process for single conference on single machine, you need change the webrtc strategy in cluster_manage.toml to `randomly-pick` or `round-robin` after multiple agents started.
The current single process of webrtc-agent may not fully use your CPU multi cores.

**Comment by caikunru** [comment]
在同一台机器上是不能启动两个webrtc-agent的需要修改启动代码才可以。
我感觉你们的问题不是这样就可以解决的，上次的那个测试其实cpu使用率也不低的，还有线程数也非常的多，这些都是不合理的问题。希望你们能够好好的测试下。如果你们愿意，我们可以从公司的层面进行合作，我也很高兴促成这件好事。如果可以，请发邮件沟通！

**Comment by lzhai** [comment]
@caikunru You can contact webrtc_support@intel.com on potential corporate level collaboration.

**Comment by starwarfan** [comment]
#494

**Comment by starwarfan** [comment]
We've changed some code to solve this issue, will close this if you don't meet this in latest 4.3.x branch.

**Comment by caikunru** [comment]
thank you
