### ISSUE TITLE
Issue in disconnection SFU Mode

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#508]
Dear Team, 

we are using version MCU  4.2.1 CentOS Package  we had reports from 4 independent (not in the same call) users that they had audio problems with calls with about 5 to 9 participants. Some participants could not hear another participant, while other could hear him. They have used mostly Chrome and Safari, no FF. Any similar experiences?

One more fact, it happens while in call, so suddenly the audio/video from one participant stops to be sent to some of the others. If the participant leaves and re-enters everyone can hear him again

This problem happnes very frequently  now..

Thanks

**Comment by starwarfan** [comment]
Hi,
were there any errors in his web console when one participant could not be heard?

**Comment by Alex-YddeR** [comment]
Ice Disconnection logs been seen.
