### ISSUE TITLE
When can Expect New Release

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#509]
Dear Team,

It's been long time since new version is released after v.4.3. when can we expect next release as many  users facing trouble in stability and scaling issues. we have many users posting in Intel WebRTC forum regarding the same.

Thanks
Naresh

**Comment by starwarfan** [comment]
Hi,
We plan to release 4.3.1 in June.

**Comment by kurapatijayaram** [comment]
👍 Waiting
