### ISSUE TITLE
MCU v4.2 CentOS Portal Stopped unexpectedly with JavaScript heap out of memory

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#519]
Dear Team,

Portal Suddenly stopped unexpectedly and below are logs
<--- Last few GCs --->

[5603:0x2682940] 2022588942 ms: Mark-sweep 1299.6 (1426.2) -> 1299.6 (1426.2) MB, 1230.9 / 0.0 ms  allocation failure GC in old space requested
[5603:0x2682940] 2022590796 ms: Mark-sweep 1299.6 (1426.2) -> 1299.5 (1426.2) MB, 1727.3 / 0.0 ms  last resort GC in old space requested
[5603:0x2682940] 2022592509 ms: Mark-sweep 1299.5 (1426.2) -> 1299.5 (1426.2) MB, 1713.5 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x15aed21258b9 <JSObject>
    1: listOnTimeout [timers.js:~231] [pc=0x152e1f8905aa](this=0x2fb94ebd0289 <Timer map = 0x27d681aef549>)

==== Details ================================================

[1]: listOnTimeout [timers.js:~231] [pc=0x152e1f8905aa](this=0x2fb94ebd0289 <Timer map = 0x27d681aef549>) {
// optimized frame
--------- s o u r c e   c o d e ---------
function listOnTimeout() {\x0a  var list = this._list;\x0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - <--- Last few GCs --->

[5603:0x2682940] 2022588942 ms: Mark-sweep 1299.6 (1426.2) -> 1299.6 (1426.2) MB, 1230.9 / 0.0 ms  allocation failure GC in old space requested
[5603:0x2682940] 2022590796 ms: Mark-sweep 1299.6 (1426.2) -> 1299.5 (1426.2) MB, 1727.3 / 0.0 ms  last resort GC in old space requested
[5603:0x2682940] 2022592509 ms: Mark-sweep 1299.5 (1426.2) -> 1299.5 (1426.2) MB, 1713.5 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x15aed21258b9 <JSObject>
    1: listOnTimeout [timers.js:~231] [pc=0x152e1f8905aa](this=0x2fb94ebd0289 <Timer map = 0x27d681aef549>)

==== Details ================================================

[1]: listOnTimeout [timers.js:~231] [pc=0x152e1f8905aa](this=0x2fb94ebd0289 <Timer map = 0x27d681aef549>) {
// optimized frame
--------- s o u r c e   c o d e ---------
function listOnTimeout() {\x0a  var list = this._list;\x0...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x8ccf9c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, int) [node]
 6: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::TurboAssembler*, v8::internal::EhFrameWriter*, v8::internal::CompilationInfo*, v8::internal::Handle<v8::internal::Object>) [node]
 7: v8::internal::compiler::CodeGenerator::FinalizeCode() [node]
 8: v8::internal::compiler::PipelineImpl::FinalizeCode() [node]
 9: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [node]
10: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [node]
11: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [node]
12: v8::internal::StackGuard::HandleInterrupts() [node]
13: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [node]
14: 0x152e11f042fd

 heap out of memory
 1: node::Abort() [node]
 2: 0x8ccf9c [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewCode(v8::internal::CodeDesc const&, unsigned int, v8::internal::Handle<v8::internal::Object>, bool, int) [node]
 6: v8::internal::CodeGenerator::MakeCodeEpilogue(v8::internal::TurboAssembler*, v8::internal::EhFrameWriter*, v8::internal::CompilationInfo*, v8::internal::Handle<v8::internal::Object>) [node]
 7: v8::internal::compiler::CodeGenerator::FinalizeCode() [node]
 8: v8::internal::compiler::PipelineImpl::FinalizeCode() [node]
 9: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [node]
10: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [node]
11: v8::internal::OptimizingCompileDispatcher::InstallOptimizedFunctions() [node]
12: v8::internal::StackGuard::HandleInterrupts() [node]
13: v8::internal::Runtime_StackGuard(int, v8::internal::Object**, v8::internal::Isolate*) [node]
14: 0x152e11f042fd

**Comment by starwarfan** [comment]
Hi, can you provide steps to reproduce this issue? So we can address the problem.

**Comment by Alex-YddeR** [comment]
Cannot reproduce this. it happens some times rare, what are the errors about? faced this issue again attached complete logs 

[portallogs.docx](https://github.com/open-webrtc-toolkit/owt-server/files/4707271/portallogs.docx)

**Comment by starwarfan** [comment]
Hi, the error means your process's memory has reach the limit.
You can try to add options to "node" command when starting portal in "bin/daemon.sh" like
"node --max_old_space_size=8000  ."

**Comment by Alex-YddeR** [comment]
How do i do this, can you me an example. 
can we add like this **export NODE_OPTIONS=--max_old_space_size=16000**
