### ISSUE TITLE
Cannot change publish permission on-the-fly for a particular participant

### ISSUE THREAD

**Issue by MrSmith87** [open-webrtc-toolkit/owt-server#537]
Hello Team,

I wanted to change the Audio-publication permission for a particular participant during an ongoing call. I used the participant update API for the same. However it seems to have following 2 bugs.

1.  Instead of updating permissions for that particular participant, it updated the permission for all the participants in the room which had the same role.

2.  If a participant is already publishing an Audio-Video stream and we update the permission on the fly by say changing video permissions to false, the video stream was still received in the room. I think the changes were not reflecting in the streams in real time. Is it a bug or the actual behaviour?

Sumit

**Comment by starwarfan** [comment]
Hi, 
for 1 it's a bug, for 2 it's actual behavior.

**Comment by MrSmith87** [comment]
Hi,
Thanks a lot for your quick repsonse.
So, I will wait for a fix for 1.

Regarding 2:
 So, in order to mute someone in an ongoing call, instead of updating the participant, I would need to filter out the forwarded stream of that particular user by looping through all the streams in the room, and then update the stream by updating its audio/video active status. is that the only way?

**Comment by starwarfan** [comment]
Hi,
You're right. It's the only way through current API.

**Comment by starwarfan** [comment]
Hi, we didn't reproduce the issue "updating permission takes effect on role instead of participant" on latest 4.3.x branch. Which branch were you using?
