### ISSUE TITLE
Does the 'Intel® Media SDK' help the audio mixing performance?

### ISSUE THREAD

**Issue by arafath-mk** [open-webrtc-toolkit/owt-server#543]
In an **audio only** conference/meeting (that is, there is no video, all participants use audio), does the **hardware acceleration** have any role? or all the audio mixing are done in the CPU itself?

**Comment by taste1981** [comment]
Intel Media SDK is not used for audio mixing acceleration in owt server. It's pure CPU-based.

**Comment by arafath-mk** [comment]
Does the conference server use CPU level acceleration using SSE or AVX for audio mixing?

**Comment by taste1981** [comment]
> Thanks for the reply. One more question. Does the conference server use CPU level acceleration using SSE or AVX for audio mixing?

The resampler part of audio mixer is SSE instrumented.  Mixing part is not.

**Comment by arafath-mk** [comment]
Thanks for the quick reply. Is the mixing part implementable in SSE or AVX? Does it give performance benefits?

**Comment by taste1981** [comment]
yes it's doable and should be able to reduce the large "for" loop for audio mixing(that adds up all source buffers sample-per-sample). But according to our profiling result we're not seeing the mixer as the hotspot. If with vtune you're observing in certain scenario this becomes hotspot, then an SIMD optimization will need to placed here.

**Comment by arafath-mk** [comment]
Thanks. Can it be useful to increase the number of participants per server? That is, for example, if CPU of a single server is fully loaded when number of participants is 100 for an audio only conference, then can it be helpful to accommodate around 400 participants?

**Comment by taste1981** [comment]
No one will implement a mixer that will allow all participants to be mixed in.  Consider the mixing will take time and you apparently need to make sure all audio processing on server side is  finished in ms time range.
So almost every implementation will perform VAD and make also make sure a limited number of active participants with most voice energy is mixed in.  Besides, as the mixer need to remove the audio from the same publisher if that participant is subscribing the mixed audio stream, so for 400 participants you've 400 mixer if yo don't mix active speaker only. I believe you don't want to do that considering scalability.
