### ISSUE TITLE
[Deprecation] Your partner is negotiating an obsolete (D)TLS version. Support for this will be removed in M81, around April 2020. Please check with your partner to have this fixed.

### ISSUE THREAD

**Issue by dzj0352** [open-webrtc-toolkit/owt-server#544]
owt-server already open TLS1.2 ,but it still warn，configuration  socket.io ssl ,warn still  exist，it can't disappear ，why ？ How to solve it ？

**Comment by starwarfan** [comment]
Hi,
Did you use the latest branch 4.2.x, 4.3.x or master?
And have you tried with latest chrome M83?

**Comment by dzj0352** [comment]
> Hi,
> Did you use the latest branch 4.2.x, 4.3.x or master?
> And have you tried with latest chrome M83?

4.3 master 
chrom version  83.0.4103.97

**Comment by dzj0352** [comment]
4.3
chrom version 83.0.4103.97

**Comment by dzj0352** [comment]
> Hi,
> Did you use the latest branch 4.2.x, 4.3.x or master?
> And have you tried with latest chrome M83?

4.3
chrom version 83.0.4103.97

**Comment by starwarfan** [comment]
Hi,
We can't reproduce it on latest 4.3.x branch. You can run installDeps.sh to update dependency on latest 4.3.x before building and have a try again.
