### ISSUE TITLE
How to customize the background

### ISSUE THREAD

**Issue by beijing-penguin** [open-webrtc-toolkit/owt-server#561]
![bg](https://user-images.githubusercontent.com/10703753/86198185-9f8db780-bb89-11ea-91da-8b8c85d6088a.png)
when i  close the camera,how can i change the default background picture ?

**Comment by daijh** [comment]
- Check the avatar configuration in "video_agent/agent.toml"
```bash
[avatar]
#widthxheight between the two dot ("180x180" between the "avatar." and ".yuv" in the default) in the location indicates the image size
location = "avatars/avatar_blue.180x180.yuv"
```

- Choose the background image size. The higher image size the better quality, the more CPU computation

- The image size was included in name,  e.g. avatar_blue.**_180x180_**.yuv

- Create yuv image with FFmpeg, or any other tools
```bash
FFmpeg -i your_backgroung_image.jpg[png] -pix_fmt yuv420p -s 180x180 avatar.180x180.yuv
```

- Reconfigure  "video_agent/agent.toml" -> "avatar" -> "location" with new yuv file

**Comment by beijing-penguin** [comment]
> * Check the avatar configuration in "video_agent/agent.toml"
> 
> ```shell
> [avatar]
> #widthxheight between the two dot ("180x180" between the "avatar." and ".yuv" in the default) in the location indicates the image size
> location = "avatars/avatar_blue.180x180.yuv"
> ```
> 
> * Choose the background image size. The higher image size the better quality, the more CPU computation
> * The image size was included in name,  e.g. avatar_blue.**_180x180_**.yuv
> * Create yuv image with FFmpeg, or any other tools
> 
> ```shell
> ffmpeg -i your_backgroung_image.jpg[png] -pix_fmt yuv420p -s 180x180 avatar.180x180.yuv
> ```
> 
> * Reconfigure  "video_agent/agent.toml" -> "avatar" -> "location" with new yuv file

ths you answer.
if i  want to change the background for every people,how can i do?

**Comment by beijing-penguin** [comment]
![image](https://user-images.githubusercontent.com/10703753/86214801-38cec500-bbae-11ea-8b01-33a4be3bad46.png)
@daijh  i find some code，and Can make this  streamId bind different backgrounds?

**Comment by daijh** [comment]
The original design is not for such usage, that each participant using different avatar. It needs to be implemented by developers.

Yes.  You need to manage the map between streamid and its avatar, and let video mixer is able to fetch correct avatar.

**Comment by beijing-penguin** [comment]
> The original design is not for such usage, that each participant using different avatar. It needs to be implemented by developers.
> 
> Yes. You need to manage the map between streamid and its avatar, and let video mixer is able to fetch correct avatar.

today,I test that code , but be missed. Could you help me find the right code place?
