### ISSUE TITLE
Issue In GPU MCU 

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#578]
Dear Team,

We are using Below hardware server for GPU MCU
E-2288G Single CPU Servers with Intel UHD Graphics P630.
Operating System: ubuntu 18.04 LTS or Centos 7.8
Intel CS Server Details: Intel CS Version 4.2.1.

We have around 25 users logged in with mix at standard resolution and output resolution at 1280x720 at 1024 Kbps

When we try to disable video and enable several times the  blue Avatar gets zoomed completly in some time and later as soon as someone  mute video all the Videos freeze but if we dont use hardware accelerator then it works fine. But using hardware acceleration gives better Quality so want help to solve this issue.

After this issue even only 4 participants in the room will have the same issue

Below are the some logs

Error in video agent as below logs
2020-06-27 21:33:32,062 - ERROR: mcu.media.MsdkVideoCompositor.MsdkVpp - (0x25962e0)Composite failed, ret -15
2020-06-27 21:33:32,102 - ERROR: mcu.media.MsdkVideoCompositor.MsdkVpp - (0x25962e0)Input -2(5): mfx vpp error, ret -16
2020-06-27 21:33:32,102 - ERROR: mcu.media.MsdkVideoCompositor.MsdkVpp - (0x25962e0)Composite failed, ret -16
2020-06-27 21:33:32,142 - ERROR: mcu.media.MsdkVideoCompositor.MsdkVpp - (0x25962e0)Input -4(5): mfx vpp error, ret -15
2020-06-27 21:33:32,142 - ERROR: mcu.media.MsdkVideoCompositor.MsdkVpp - (0x25962e0)Composite failed, ret -15
2020-06-27 21:33:32,182 - ERROR: mcu.media.MsdkVideoCompositor.MsdkVpp - (0x25962e0)Input -2(5): mfx vpp error, ret -16
2020-06-27 21:33:32,182 - ERROR: mcu.media.MsdkVideoCompositor.MsdkVpp - (0x25962e0)Composite failed, ret -16

CPU Info

Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 8
On-line CPU(s) list: 0-7
Thread(s) per core: 2
Core(s) per socket: 4
Socket(s): 1
NUMA node(s): 1
Vendor ID: GenuineIntel
CPU family: 6
Model: 94
Model name: Intel(R) Xeon(R) CPU E3-1585L v5 @ 3.00GHz
Stepping: 3
CPU MHz: 899.897
CPU max MHz: 3700.0000
CPU min MHz: 800.0000
BogoMIPS: 6000.00
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 8192K
NUMA node0 CPU(s): 0-7

Media SDK Version: 18.14.0 OS : Ubuntu 18.04 VA Info:
libva info: VA-API version 1.4.0 libva info: va_getDriverName() returns 0 libva info: User requested driver 'iHD' libva info: Trying to open /opt/intel/mediasdk/lib64/iHD_drv_video.so libva info: Found init function __vaDriverInit_1_4 libva info: va_openDriver() returns 0 vainfo: VA-API version: 1.4 (libva 2.1.0) vainfo: Driver version: Intel iHD driver - 18.4.git_e61f5c_2019-01-29 vainfo: Supported profile and entrypoints VAProfileNone : VAEntrypointVideoProc VAProfileNone : VAEntrypointStats VAProfileMPEG2Simple : VAEntrypointVLD VAProfileMPEG2Simple : VAEntrypointEncSlice VAProfileMPEG2Main : VAEntrypointVLD VAProfileMPEG2Main : VAEntrypointEncSlice VAProfileH264Main : VAEntrypointVLD VAProfileH264Main : VAEntrypointEncSlice VAProfileH264Main : VAEntrypointFEI VAProfileH264Main : VAEntrypointEncSliceLP VAProfileH264High : VAEntrypointVLD VAProfileH264High : VAEntrypointEncSlice VAProfileH264High : VAEntrypointFEI VAProfileH264High : VAEntrypointEncSliceLP VAProfileVC1Simple : VAEntrypointVLD VAProfileVC1Main : VAEntrypointVLD VAProfileVC1Advanced : VAEntrypointVLD VAProfileJPEGBaseline : VAEntrypointVLD VAProfileJPEGBaseline : VAEntrypointEncPicture VAProfileH264ConstrainedBaseline: VAEntrypointVLD VAProfileH264ConstrainedBaseline: VAEntrypointEncSlice VAProfileH264ConstrainedBaseline: VAEntrypointFEI VAProfileH264ConstrainedBaseline: VAEntrypointEncSliceLP VAProfileVP8Version0_3 : VAEntrypointVLD VAProfileHEVCMain : VAEntrypointVLD VAProfileHEVCMain : VAEntrypointEncSlice VAProfileHEVCMain : VAEntrypointFEI

Thanks

**Comment by lzhai** [comment]
We can reproduce this issue, will look into it and update the progress.

**Comment by Alex-YddeR** [comment]
Hi,  

Are you able to fix the issue?

Thanks

**Comment by Alex-YddeR** [comment]
Hi Team,

Any update on this?

Thanks

**Comment by Alex-YddeR** [comment]
Hi Team,

Any updates please.have we able to fix this issue.

Thanks

**Comment by daijh** [comment]
@Alex-YddeR the status was updated on #556
Let's merge these 2 issues for future discussion.
