### ISSUE TITLE
sip not working when MCU behind NAT

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#580]
Dear Team,

Hosting Details:

OS: CentOS 7.8 or Ubuntu 18.04LTS
Intel webRTC Version: 4.2.1 Software Accelerated Hosted on AWS Behind NAT.
Kamailio: Hosted on  Direct Public Network Version kamailio 5.3.5 (x86_64/linux)

When MCU Room registered to kamailio its getting registered with private IP of the MCU. when we make a call to SIP endpoint  there is no call established, same MCU when hosted on direct public IP it works .

Also can we enable H264 HP and Baseline Codec with software accelerated MCU.

Thanks
Naresh

**Comment by lzhai** [comment]
1. Currently MCU doesn't support NAT traverse with SIP call like the WebRTC call.
2. For hardware accelerated MCU, we use Intel Media SDK for encoding, then H.264 HiProfile is supported. For software MCU, we use free Open H264, HiProfile encoding is not in the supporting list.
