### ISSUE TITLE
WARN: mcu.media.AcmEncoder - (0x26445f0)Too many pending frames(3)

### ISSUE THREAD

**Issue by beijing-penguin** [open-webrtc-toolkit/owt-server#585]
What is the effect of this WARN?

**Comment by daijh** [comment]
audio encoder is too slow, that >3 frame in the queue. Possible frames drop.

**Comment by beijing-penguin** [comment]
> audio encoder is too slow, that >3 frame in the queue. Possible frames drop.

ok,ths..
