### ISSUE TITLE
修改mongo配置后报错after modify [mongo] toml,,,getRooms failed( 401 ): {"error":{"code":1101,"message":"WWW-Authenticate: MAuth realm=\"http://marte3.dit.upm.es\""}}

### ISSUE THREAD

**Issue by beijing-penguin** [open-webrtc-toolkit/owt-server#609]
I have modified portal.toml,conference_agent/agent,management_api/management_api.toml,potal/potal.toml,sip_portal/sip_potal.toml config file at the same time..for modify [mongo]....eg:

[mongo]
dataBaseURL = "192.168.72.140/owtdb" #default: "localhost/owtdb"

I make sure，the mongo config is connected success.
then run start-all.sh ,,got error,eg:
![image](https://user-images.githubusercontent.com/10703753/90627011-212ac900-e24e-11ea-8193-82e99ea84c1d.png)

**Comment by starwarfan** [comment]
Have you run init script with your updated dataBaseUrl in management_api?

**Comment by beijing-penguin** [comment]
> 您是否在management_api中使用更新的dataBaseUrl运行初始化脚本？
> 看到`management_api/init.sh`

before,，i have  excuted  (cd dist && ./bin/init-all.sh && ./bin/start-all.sh)   ,but when i excuted again, i found that the management_api.toml was automatically-modifying modified 

Current:
[mongo]
dataBaseURL = "192.168.72.140/owtdb"

be automatically-modifying modified  
[mongo]
dataBaseURL = "localhost/owtdb"

**Comment by beijing-penguin** [comment]
> Have you run init script with your updated dataBaseUrl in management_api?
> See `management_api/init.sh`

I found reason,  management_api/init.sh file must be modified DB_URL='192.168.72.140/owtdb' at 10 line...and ok...
