### ISSUE TITLE
 google-chrome-stable update issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#613]
1,Compile and package the latest master's mcu, and 4.3.x mcu, and start
2,Chrome just updated 85 today, connecting master and 4.3.x mcu, found that publish failed
grep error logs -ri:
ogs/webrtc-c60744737d011319cdbe@10.239.61.95_0.log:2020-08-26 14:43:51,472  - WARN: dtls.SSL - failed in error
logs/webrtc-c60744737d011319cdbe@10.239.61.95_0.log:2020-08-26 14:43:51,472  - ERROR: dtls.DtlsSocket - SSL error 1
logs/webrtc-c60744737d011319cdbe@10.239.61.95_0.log:2020-08-26 14:43:51,472  - WARN: dtls.DtlsSocketContext - DTLS Handshake Failure error:1410241A:SSL routines:dtls1_read_bytes:tlsv1 alert decode error
logs/webrtc-c60744737d011319cdbe@10.239.61.95_0.log:2020-08-26 14:43:51,472  - WARN: DtlsTransport - id: 844355771258214400,  message: Handshake failed, transportName:video, openSSLerror: error:1410241A:SSL routines:dtls1_read_bytes:tlsv1 alert decode error
logs/webrtc-c60744737d011319cdbe@10.239.61.95_0.log:2020-08-26 14:43:51,472  - ERROR: WebRtcConnection - id: 844355771258214400,  message: Transport Failed, transportType: video
logs/webrtc-c60744737d011319cdbe@10.239.61.95_1.log:2020-08-26 14:43:54,582  - WARN: dtls.SSL - failed in error
logs/webrtc-c60744737d011319cdbe@10.239.61.95_1.log:2020-08-26 14:43:54,582  - ERROR: dtls.DtlsSocket - SSL error 1
logs/webrtc-c60744737d011319cdbe@10.239.61.95_1.log:2020-08-26 14:43:54,582  - WARN: dtls.DtlsSocketContext - DTLS Handshake Failure error:1410241A:SSL routines:dtls1_read_bytes:tlsv1 alert decode error
logs/webrtc-c60744737d011319cdbe@10.239.61.95_1.log:2020-08-26 14:43:54,582  - WARN: DtlsTransport - id: 419034508232349250,  message: Handshake failed, transportName:video, openSSLerror: error:1410241A:SSL routines:dtls1_read_bytes:tlsv1 alert decode error
logs/webrtc-c60744737d011319cdbe@10.239.61.95_1.log:2020-08-26 14:43:54,582  - ERROR: WebRtcConnection - id: 419034508232349250,  message: Transport Failed, transportType: video

**Comment by taste1981** [comment]
make sure you update your dependency of licode by installing it again via installDeps script.  We added patch recently on both 4.3.x and master to handle this actually.

**Comment by nareshinstavc** [comment]
Any Patch for MCU version 4.2.1

Thanks

**Comment by beijing-penguin** [comment]
> Any Patch for MCU version 4.2.1
> 
> Thanks

how to add Patch?

**Comment by Alex-YddeR** [comment]
Is master branch is stable enough compare to 4.3.x??

Thanks

**Comment by cisco66666** [comment]
It has been resolved. After downloading the latest code, update licode, and then compile and package, which is suitable for mcu of each branch
________________________________
发件人: Alex-YddeR <notifications@github.com>
发送时间: 2020年8月27日 21:12
收件人: open-webrtc-toolkit/owt-server <owt-server@noreply.github.com>
抄送: Zhao, JinpengX <jinpengx.zhao@intel.com>; State change <state_change@noreply.github.com>
主题: Re: [open-webrtc-toolkit/owt-server] google-chrome-stable update issue (#613)


Is master branch is stable enough compare to 4.3.x??

Thanks

―

**Comment by starwarfan** [comment]
See
#595 #594 #599
