### ISSUE TITLE
webrtc-agent crash (SIGSEGV)

### ISSUE THREAD

**Issue by digitalix** [open-webrtc-toolkit/owt-server#618]
I'm trying to deploy OWT on my k8s cluster and it partially works but as soon as I join a room webrtc agent will crash.

Here is the log:
https://pastebin.com/XmN95h68

I'm using master branch and I've tested it running on a VM and it's fine.

Any suggestions?

**Comment by digitalix** [comment]
I was able to find a solution, later I'll create push request with the fix.

**Comment by kurapatijayaram** [comment]
+1

**Comment by starwarfan** [comment]
Did you build latest master branch with node v10, openssl 1.1 and rebuild your libsrtp before building?

**Comment by kurapatijayaram** [comment]
Hi @starwarfan ,
Master branch means v4.3.1 only right ? But in the documentation it was strictly specified to use v8.15.

https://software.intel.com/sites/products/documentation/webrtc/conference/

Thank you.

**Comment by digitalix** [comment]
> Did you build latest master branch with node v10, openssl 1.1 and rebuild your libsrtp before building?

I was building it with node v10 since the beginning but didn't know about OpenSSL, and libre and they were outdated in the docker file. After a few hours, I compared the sh install files with docker and that's how I figured it out.

Here is my PR with a fix for it. https://github.com/open-webrtc-toolkit/owt-server/pull/621

**Comment by kurapatijayaram** [comment]
I tried with node v10 , it didnt worked, again same issue.
