### ISSUE TITLE
building 4.2.x branch having issue in build

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#624]
Dear Team,

building 4.2.x branch having issue in build, below logs. kindly help on this.

./erizo/src/erizo/dtls/DtlsSocket.h:5:26: fatal error: srtp2/srtp.h: No such file or directory
   #include <srtp2/srtp.h>
                          ^
compilation terminated.
make: *** [Release/obj.target/webrtc/erizo/src/erizo/DtlsTransport.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/home/centos/owt-server/source/agent/webrtc/webrtcLib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-1062.12.1.el7.x86_64
gyp ERR! command "/usr/bin/node" "/bin/node-gyp" "build" "-j" "8" "--loglevel=error"
gyp ERR! cwd /home/centos/owt-server/source/agent/webrtc/webrtcLib
gyp ERR! node -v v8.17.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp build -j 8 --loglevel=error
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at buildTarget (/home/centos/owt-server/scripts/build.js:129:5)
    at buildList.map (/home/centos/owt-server/scripts/build.js:153:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/centos/owt-server/scripts/build.js:152:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

Thanks
Alex

**Comment by Alex-YddeR** [comment]
Any update on this issue.

Thanks
Naresh

**Comment by Alex-YddeR** [comment]
In file included from ../../MsdkVideoCompositor.cpp:10:0:
/home/ubuntu/owt-server/source/core/owt_base/MsdkBase.h:13:10: fatal error: mfx/mfxdefs.h: No such file or directory
 #include <mfx/mfxdefs.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
videoMixer-msdk.target.mk:148: recipe for target 'Release/obj.target/videoMixer-msdk/../MsdkVideoCompositor.o' failed
make: *** [Release/obj.target/videoMixer-msdk/../MsdkVideoCompositor.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from ../../../../../core/owt_base/FrameConverter.h:18:0,
                 from ../../../../../core/owt_base/FrameConverter.cpp:5:
../../../../../core/owt_base/MsdkBase.h:13:10: fatal error: mfx/mfxdefs.h: No such file or directory
 #include <mfx/mfxdefs.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
videoMixer-msdk.target.mk:148: recipe for target 'Release/obj.target/videoMixer-msdk/../../../../core/owt_base/FrameConverter.o' failed
make: *** [Release/obj.target/videoMixer-msdk/../../../../core/owt_base/FrameConverter.o] Error 1
In file included from /home/ubuntu/owt-server/source/core/owt_base/FrameConverter.h:18:0,
                 from ../../SoftVideoCompositor.h:22,
                 from ../../VideoFrameMixerImpl.h:15,
                 from ../../VideoMixer.cpp:9:
/home/ubuntu/owt-server/source/core/owt_base/MsdkBase.h:13:10: fatal error: mfx/mfxdefs.h: No such file or directory
 #include <mfx/mfxdefs.h>
          ^~~~~~~~~~~~~~~
compilation terminated.
videoMixer-msdk.target.mk:148: recipe for target 'Release/obj.target/videoMixer-msdk/../VideoMixer.o' failed
make: *** [Release/obj.target/videoMixer-msdk/../VideoMixer.o] Error 1
make: Leaving directory '/home/ubuntu/owt-server/source/agent/video/videoMixer/videoMixer_msdk/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v8.15.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 5.3.0-1032-aws
gyp ERR! command "/root/.nvm/versions/node/v8.15.0/bin/node" "/root/.nvm/versions/node/v8.15.0/bin/node-gyp" "build" "-j" "8" "--loglevel=error"
gyp ERR! cwd /home/ubuntu/owt-server/source/agent/video/videoMixer/videoMixer_msdk
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp build -j 8 --loglevel=error
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at buildTarget (/home/ubuntu/owt-server/scripts/build.js:129:5)
    at buildList.map (/home/ubuntu/owt-server/scripts/build.js:153:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/ubuntu/owt-server/scripts/build.js:152:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
root@ip-192-168-1-142:/home/ubuntu/owt-server#

**Comment by daijh** [comment]
HW MCU depends on Intel-Media-SDK, you need to install Intel-Media-SDK first as described in DOC.
Or you can build SW MCU only,  
```bash
./scripts/build.js -t mcu
```

**Comment by Alex-YddeR** [comment]
Installing nicer? [No/yes]Yes
Cloning into 'nICEr'...
remote: Enumerating objects: 376, done.
remote: Counting objects: 100% (376/376), done.
remote: Compressing objects: 100% (109/109), done.
remote: Total 866 (delta 269), reused 372 (delta 267), pack-reused 490
Receiving objects: 100% (866/866), 593.62 KiB | 317.00 KiB/s, done.
Resolving deltas: 100% (586/586), done.
HEAD is now at 24d88e9 Add ICE FAILED as a possible pair state when nominating a pair
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /home/centos/owt4.2.x/owt-server/build/libdeps/build/bin/gcc
-- Check for working C compiler: /home/centos/owt4.2.x/owt-server/build/libdeps/build/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/centos/owt4.2.x/owt-server/build/libdeps/build/bin/g++
-- Check for working CXX compiler: /home/centos/owt4.2.x/owt-server/build/libdeps/build/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/centos/owt4.2.x/owt-server/third_party/nICEr
Scanning dependencies of target project_nrappkit
[  2%] Creating directories for 'project_nrappkit'
[  4%] Performing download step (git clone) for 'project_nrappkit'
Cloning into 'project_nrappkit'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 269 (delta 35), reused 37 (delta 9), pack-reused 205
Receiving objects: 100% (269/269), 207.86 KiB | 348.00 KiB/s, done.
Resolving deltas: 100% (148/148), done.
Already on 'master'
[  6%] No patch step for 'project_nrappkit'
[  9%] Performing update step for 'project_nrappkit'
Already on 'master'
[ 11%] Performing configure step for 'project_nrappkit'
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /home/centos/owt4.2.x/owt-server/build/libdeps/build/bin/gcc
-- Check for working C compiler: /home/centos/owt4.2.x/owt-server/build/libdeps/build/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/centos/owt4.2.x/owt-server/build/libdeps/build/bin/g++
-- Check for working CXX compiler: /home/centos/owt4.2.x/owt-server/build/libdeps/build/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:7 (message):
  lib not found: SSL-NOTFOUND check README
Call Stack (most recent call first):
  CMakeLists.txt:89 (test_lib)


-- Configuring incomplete, errors occurred!
See also "/home/centos/owt4.2.x/owt-server/third_party/nICEr/third_party/nrappkit/src/project_nrappkit-build/CMakeFiles/CMakeOutput.log".
make[2]: *** [third_party/nrappkit/src/project_nrappkit-stamp/project_nrappkit-configure] Error 1
make[1]: *** [CMakeFiles/project_nrappkit.dir/all] Error 2
make: *** [all] Error 2

**Comment by starwarfan** [comment]
Hi,
OWT does not use nicer, please select the default option 'No' and have a try.

**Comment by Alex-YddeR** [comment]
Then we get in building below error

./WebRtcConnection.cc: In member function ‘virtual void StatCallWorker::HandleOKCallback()’:
../WebRtcConnection.cc:42:25: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(int, v8::Local<v8::Value>*) const’ is deprecated (declared at ../../../../../node_modules/nan/nan.h:1655) [-Wdeprecated-declarations]
   callback->Call(1, argv);
                         ^
../WebRtcConnection.cc: In static member function ‘static void WebRtcConnection::eventsCallback(uv_async_t*)’:
../WebRtcConnection.cc:707:102: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../../../../node_modules/nan/nan.h:958) [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), obj->eventCallback_->GetFunction(), 2, args);
                                                                                                      ^
../WebRtcConnection.cc: In static member function ‘static void WebRtcConnection::statsCallback(uv_async_t*)’:
../WebRtcConnection.cc:722:104: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../../../../node_modules/nan/nan.h:958) [-Wdeprecated-declarations]
       Nan::MakeCallback(Nan::GetCurrentContext()->Global(), obj->statsCallback_->GetFunction(), 1, args);
                                                                                                        ^
../VideoFrameConstructorWrapper.cc: In static member function ‘static void VideoFrameConstructor::Callback(uv_async_t*)’:
../VideoFrameConstructorWrapper.cc:152:97: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated (declared at ../../../../../node_modules/nan/nan.h:958) [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::GetCurrentContext()->Global(), obj->Callback_->GetFunction(), 1, args);
                                                                                                 ^
  CXX(target) Release/obj.target/webrtc/conn_handler/WoogeenHandler.o
  CXX(target) Release/obj.target/webrtc/erizo/src/erizo/DtlsTransport.o
In file included from ../erizo/src/erizo/DtlsTransport.h:11:0,
                 from ../erizo/src/erizo/DtlsTransport.cpp:5:
../erizo/src/erizo/dtls/DtlsSocket.h:5:26: fatal error: srtp2/srtp.h: No such file or directory
   #include <srtp2/srtp.h>
                          ^
compilation terminated.
make: *** [Release/obj.target/webrtc/erizo/src/erizo/DtlsTransport.o] Error 1
make: *** Waiting for unfinished jobs....
make: Leaving directory `/home/centos/owt4.2.x/owt-server/source/agent/webrtc/webrtcLib/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.10.0-1127.19.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/bin/node-gyp" "build" "-j" "8" "--loglevel=error"
gyp ERR! cwd /home/centos/owt4.2.x/owt-server/source/agent/webrtc/webrtcLib
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:650
    throw err;
    ^

Error: Command failed: node-gyp build -j 8 --loglevel=error
    at checkExecSyncError (child_process.js:607:13)
    at execSync (child_process.js:647:13)
    at buildTarget (/home/centos/owt4.2.x/owt-server/scripts/build.js:129:5)
    at buildList.map (/home/centos/owt4.2.x/owt-server/scripts/build.js:153:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/centos/owt4.2.x/owt-server/scripts/build.js:152:23)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)

Thanks
Alex

**Comment by Alex-YddeR** [comment]
^
[1222/1331] CXX obj/webrtc/modules/video_coding/webrtc_h264/h264.o
FAILED: obj/webrtc/modules/video_coding/webrtc_h264/h264.o 
g++ -MMD -MF obj/webrtc/modules/video_coding/webrtc_h264/h264.o.d -DWEBRTC_USE_H264 -DWEBRTC_INITIALIZE_FFMPEG -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DWEBRTC_ENABLE_PROTOBUF=0 -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DEXPAT_RELATIVE_PATH -DWEBRTC_POSIX -DWEBRTC_LINUX -DWEBRTC_BUILD_LIBEVENT -I/home/centos/4.2.x/owt-server/build/libdeps/build/include -I/home/centos/4.2.x/owt-server/third_party/openh264 -I.. -Igen -I../third_party/libyuv/include -I../webrtc/common_video/include -I../webrtc/common_video/libyuv/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -m64 -march=x86-64 -pthread -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g0 -fvisibility=hidden -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-strict-overflow -fvisibility-inlines-hidden -std=gnu++11 -Wno-narrowing -fno-rtti -fno-exceptions -Wnon-virtual-dtor -Woverloaded-virtual -c ../webrtc/modules/video_coding/codecs/h264/h264.cc -o obj/webrtc/modules/video_coding/webrtc_h264/h264.o
In file included from ../webrtc/modules/video_coding/codecs/h264/h264.cc:16:0:
../webrtc/modules/video_coding/codecs/h264/h264_encoder_impl.h:22:41: fatal error: codec/api/svc/codec_app_def.h: No such file or directory
 #include "codec/api/svc/codec_app_def.h"
                                         ^
compilation terminated.
[1231/1331] CXX obj/webrtc/modules/video_coding/webrtc_vp8/default_temporal_layers.o
ninja: build stopped: subcommand failed.
Generate libwebrtc.a OK

Thanks

**Comment by laplaceliu** [comment]
Just install `libsrtp2-dev`
```
sudo apt install libsrtp2-dev
```
