### ISSUE TITLE
mixed stream participant name on video 

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#631]
Dear Team,

Is there any way to render the name of the participant on the mixed stream

Thanks
Alex

**Comment by nikhilsmsc** [comment]
Hi team,
I tested with source code drawText  method in roomController.js 
I am trying to draw text on a particular stream id but, using drawText method but it's not working but in debugging mode logs are generating but there is no text on that stream in SFU and in mixed stream also 

Is that correct way to drawtext on particular stream ?
If possible to give name while publishing the steam
And also mix: true or false  also it is very use-full while publishing , present we are send the mix : true or false value in attributes and directly calling mixing method in conference agent 

Thanks,
Nikhil

**Comment by Larry-Arun** [comment]
hi, brothers, is the problem solved? Urgently need your help
