### ISSUE TITLE
How to control VAD time

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#633]
Dear Team,

How do we control VAD delay 

Thanks

**Comment by jayaramsmsc** [comment]
+1

**Comment by kurapatijayaram** [comment]
+1

**Comment by nikhilsmsc** [comment]
Hi,
you can change from 1000ms in  conference agent roomController.js
makeRPC(
rpcClient,
terminals[audio_mixer].locality.node,
'enableVAD',
[1000])

thanks,
Nikhil
