### ISSUE TITLE
Run "preprocess_tool" crash

### ISSUE THREAD

**Issue by dengliang2008** [open-webrtc-toolkit/owt-server#69]
Run plugin demo "preprocess_tool" crash on Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Error info as below:
./preprocess_tool 
Initializing face_detection network...
FaceDetection plugin:CPU
FaceDetection modle:/opt/intel/computer_vision_sdk/deployment_tools/intel_models/face-detection-retail-0004/FP32/face-detection-retail-0004.xml
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  dlSym cannot locate method 'CreateExtension': ./preprocess_tool: undefined symbol: CreateExtension
/opt/intel/computer_vision_sdk_2018.5.455/deployment_tools/inference_engine/include/details/os/lin_shared_object_loader.h:55
Aborted (core dumped)

**Comment by dengliang2008** [comment]
I change the device type from "GPU" to "CPU" in "owt-server/source/agent/plugins/samples/face_recognition_plugin/preprocess_tool/main.cpp"

**Comment by taste1981** [comment]
Fixed by #74
