### ISSUE TITLE
Ios and Android publish stream will be frequent caton with latest MCU

### ISSUE THREAD

**Issue by GaoMingKai** [open-webrtc-toolkit/owt-server#713]
ios devices : iphone 7plush
steps:
      user1 join room with ios.
      user2 join room with other client.
      user1 publish video(H264) audio(OPUS).
      user2 subscribe stream.
error:
        user2`s video will be frequent caton.
But 4.3.1 mcu package is normal.

**Comment by jianjunz** [comment]
Same issue as https://github.com/open-webrtc-toolkit/owt-client-javascript/issues/435?

**Comment by jianjunz** [comment]
Cannot reproduce this issue on iOS and yesterday's conference server.

**Comment by GaoMingKai** [comment]
Stuttering will occur probabilistically on the latest mcu package

**Comment by yanbin7** [comment]
Become random issue at latest MCU,  reduce priority
