### ISSUE TITLE
mix issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#750]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
1,sub mix stream
2,pub a stream with video only
3,The new stream is mixed into the mixed stream, and sub a forward stream of audio and video

Expected when sub fails, there is no flow in mix, which is not expected
3，Expected ：
mcu works normally, no crash, no error

**Comment by qwu16** [comment]
Cannot reproduce in latest code
