### ISSUE TITLE
js sample subsribe mixStream failed when click different resolution button multiply times

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-server#751]
1  js sample join room
2: client different resolution button multiply times

js console log:
[webrtctest22.sh.intel.com-1607416933487.log](https://github.com/open-webrtc-toolkit/owt-server/files/5657932/webrtctest22.sh.intel.com-1607416933487.log)

chrome version: 87
mcu: 20201206-centos

**Comment by qwu16** [comment]
cannot reproduce in latest code
