### ISSUE TITLE
After three users enter the room, the second user pub problem

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#752]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
1,User 1, pub a h264 stream, sub a forward stream
2,use 2,Repeat the above operation，pub may fail
3,use 3,Repeat the above operation，pub may fail
It is expected that pub is successful and can sub
3，Expected ：
mcu works normally, no crash, no error

**Comment by yanbin7** [comment]
Fixed, and need verify
