### ISSUE TITLE
createsipcalls failed

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#756]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
1,user sends createsipcalls request:failed
page log:
script2.js:1598 new participant joined: r {id: "SipIn1356874616150", addEventListener: ƒ, removeEventListener: ƒ, clearEventListener: ƒ, dispatchEvent: ƒ, …}
script2.js:1727 participant SipIn1356874616150 left

It is expected that createsipcalls is successful
3，Expected ：
mcu works normally, no crash, no error

**Comment by qwu16** [comment]
fixed by PR832
