### ISSUE TITLE
 Encryption packaging mcu problem

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#776]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
1,mcu encryption packaging: ./scripts/pack.js -wf --archive v5.0centosencrypt --encrypt -f --app-path $samplepath
2,Start the mcu package: ./bin/start-all.sh
3,error:
logs/conference-690023f1e52d32f84b90@10.239.44.113_0.log:2020-12-19 15:55:49.149  - INFO: AmqpClient - Connection to rabbitMQ server error ReferenceError: regeneratorRuntime is not defined
logs/management-api.stdout:"use strict";function _asyncToGenerator(e){return function(){var a=e.apply(this,arguments);return new Promise(function(c,i){return function t(e,r){try{var o=a[e](r),n=o.value}catch(e){return void i(e)}if(!o.done)return Promise.resolve(n).then(function(e){t("next",e)},function(e){t("throw",e)});c(n)}("next")})}}var validateReq=require("./restReqValidator").validate,rpc=require("./rpc/rpc"),log=require("./logger").logger.getLogger("RequestHandler"),cluster_name=((global.config||{}).cluster||{}).name||"owt-cluster",e=require("./errors"),scheduleAgent=function(o,n,e,t,c){var i=!0;(function t(r){if(r<=0)return c("timeout");rpc.callRpc(cluster_name,"schedule",[o,n,e,6e4],{callback:function(e){"timeout"===e||"error"===e?i&&(log.info("Faild in scheduling ",o," tokenCode:",n,", keep trying."),setTimeout(function(){t(r-("timeout"===e?4:1))},1e3)):(c(e.info),i=!1)}})})(t)};exports.schedulePortal=function(e,t,r){return scheduleAgent("
logs/management-api.stdout:ReferenceError: regeneratorRuntime is not defined
logs/conference-690023f1e52d32f84b90@10.239.44.113_1.log:2020-12-19 15:55:49.163  - INFO: AmqpClient - Connection to rabbitMQ server error ReferenceError: regeneratorRuntime is not defined

3，Expected ：
mcu works normally, no crash, no error

**Comment by qwu16** [comment]
Fixed by PR 825
