### ISSUE TITLE
3300/console Video Parameters KeyFrameInterval issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#779]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
1,Cancel the value of 100 of KeyFrameInterval in 3300/console
2,Open the page, you can add KeyFrameInterval to 100 when sub, which is not expected
It is expected that is successful
3，Expected ：
mcu works normally, no crash, no error

**Comment by qwu16** [comment]
Fixed in latest code
