### ISSUE TITLE
video-agent HA issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#791]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
     First scene
      1,,Device A starts all MCU modules
      2,Device B starts the video proxy and sets rabbitmq to point to device B
      3,User a connects to MCU, pub a stream, and mix to a mixed stream, sub a mix stream, the mix stream picture is normal and smooth
    4,Device A ：./bin/daemon.sh stop video-agent,      The picture is still in the mix

3，Expected ：
The screen plays normally in the mix

**Comment by qwu16** [comment]
Fixed by PR 832
