### ISSUE TITLE
portal   distributed issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#797]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
First scene
1,Deploy portal in device ADeploy all other modules in device B
2,broken net device A then restart net device A（portal join cluster successfully,and mcu works well）
3, broken net device B then restart net device B（portal join cluster successfully,and mcu works well）
4,broken net device A  and broken net device B then restart net device A and  restart net device B
5，mcu Can not work normally error：
starting portal, stdout -> /home/webrtc/Release-v5.0ubuntu20201221/logs/portal.stdout
2020-12-23 15:34:59.789  - INFO: AmqpClient - Connecting to rabbitMQ server OK, options: [Object: null prototype] { host: 'webrtc51.sh.intel.com', port: 5672 }
2020-12-23 15:34:59.867  - INFO: Main - portal initializing as rpc client ok
2020-12-23 15:34:59.917  - INFO: Main - portal join cluster ok, with rpcID: portal-96d41c89c3866f7e33ad@44.113
2020-12-23 15:34:59.918  - INFO: ClusterWorker - Join cluster owt-cluster OK.
2020-12-23 15:34:59.930  - INFO: Main - portal initializing as rpc server ok
2020-12-23 15:34:59.939  - INFO: Main - portal-96d41c89c3866f7e33ad@44.113 as monitor ready
webrtc51 ！==  44.113

logs/portal.stdout.1:2020-12-23 15:31:22.847  - ERROR: Main - portal getting token failed.
logs/portal.stdout:2020-12-23 15:35:10.190  - ERROR: Main - portal getting token failed.
logs/management-api.stdout:Save serverKey error: MongooseError: Operation `keys.findOneAndUpdate()` buffering timed out after 10000ms
logs/management-api.stdout:2020-12-23 15:22:17.931  - WARN: ManagementServer - MongooseError: Operation `services.findOne()` buffering timed out after 10000ms
logs/management-api.stdout:2020-12-23 15:22:19.988  - WARN: ManagementServer - MongooseError: Operation `services.findOne()` buffering timed out after 10000ms
logs/management-api.stdout:2020-12-23 15:22:30.140  - WARN: ManagementServer - MongooseError: Operation `services.findOne()` buffering timed out after 10000ms

3，Expected ：
portal join cluster（webrtc51.sh.intel.com===61.8） successfully,and mcu works well

**Comment by richard-romano** [comment]
@cisco66666 I know this is old but did you find a specific solution to this issue?
I'm getting the exact same errors when trying to run owt in docker using build_docker_image.sh script.
