### ISSUE TITLE
pub simulcast hd720p issue #440

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#800]
1,Environment and platform：
5.0mcu，ubuntu，software，chrome87
2,Reproduce step

scene 1
1，pub 720p simulcast stream with vp9
options = {
audio : true,
video : [
{rid: 'h', active: true, scaleResolutionDownBy: 4.0},
{rid: 'q', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true，scaleResolutionDownBy: 1.0}
]}
In the streamadded event, it was found that the remotestream stream has three rids, all of which are 320x180.

expected:
The resolutions of the three rids are: 720p, 360p, 180p

scene 2
1，pub 720p simulcast stream with h264
options = {
audio : true,
video : [
{rid: 'h', active: true, scaleResolutionDownBy: 4.0},
{rid: 'q', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true，scaleResolutionDownBy: 1.0}
]}
In the streamadded event, it was found that the remotestream stream has three rids, The resolutions of the three rids are: 360p， 360p, 180p

expected:
The resolutions of the three rids are: 720p, 360p, 180p

scene 3
1，pub 2080p simulcast stream with vp8
options = {
audio : true,
video : [
{rid: 'h', active: true, scaleResolutionDownBy: 4.0},
{rid: 'q', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true，scaleResolutionDownBy: 1.0}
]}
In the streamadded event, it was found that the remotestream stream has three rids, The resolutions of the three rids are: 237x218,474x436,948x872

expected:
The resolutions of the three rids are: {width: 1920, height: 1080}，{width: 960, height: 540}，{width: 480, height: 270}

**Comment by yanbin7** [comment]
Brower's behaves
