### ISSUE TITLE
android/windows subscribe simulcast stream with f,q, h get same min resolution in getStatus

### ISSUE THREAD

**Issue by zhangyihui1** [open-webrtc-toolkit/owt-server#803]
1: chrome and android/windows join room
2: chrome publish simulcast stream with
options = {
audio : true,
video : [
{rid: 'h', active: true, scaleResolutionDownBy: 4.0},
{rid: 'q', active: true, scaleResolutionDownBy: 2.0},
{rid: 'f', active: true，scaleResolutionDownBy: 1.0}
]}
3: android subscribe simulcast with h ,q ,f

expected:
The resolutions of the three rids are: 720p, 360p, 180p

actual:
all rid get 180p

**Comment by taste1981** [comment]
Fixed by https://github.com/open-webrtc-toolkit/owt-client-native/pull/461
