### ISSUE TITLE
update recording issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#806]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87

2，Reproduce step：
     1,User A records a mix stream,
     2,user A During recording, call updaterecording to update the mix stream（1080p） to the forward stream（720p）
     3,update recording failed 

3，Expected ：
update recording seccess and 
The recorded video plays smoothly, and you can see the scene of switching from mix to forward

**Comment by qwu16** [comment]
Specify resolution value to the one that forward stream supports
