### ISSUE TITLE
update rtmp issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#807]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87

2，Reproduce step：
1,User A pushes the mix stream to the rtmp server
2,User A calls updatertmp to update the pushed mix stream（1080p） to the forward stream（720p）
3,The above second step update rtmp failed

3，Expected ：
update rtmp seccess
The video on the rtmp server plays smoothly, and you can see the scene of switching from mix to forward

**Comment by cisco66666** [comment]
The problem is still there

**Comment by qwu16** [comment]
Specify resolution value to the one that forward stream supports
