### ISSUE TITLE
Audio / Video Issue

### ISSUE THREAD

**Issue by ashar02** [open-webrtc-toolkit/owt-server#831]
I have deployed latest code from master head on Ubuntu 18 just now. Overall server is running good. But on certain networks audio and video freezes. Here is the screenshot of webrtc internel. In same case with same network other solutions are running correctly like mediasoup or zoom... 
<img width="1625" alt="Screenshot 2020-12-28 at 9 39 41 PM" src="https://user-images.githubusercontent.com/1763187/103229642-498da700-4955-11eb-8992-c8653b61a250.png">
See in above image, packet loss is gradually increasing with time. Its because of jitter delay increase or some thing else?
Any suggestion to try and address this issue?
Here is the url I deployed on https://hype4.onescreensolutions.com:3004

**Comment by ashar02** [comment]
Can someone suggest what to try for noisy connection having 10 to 15 percent loss?

**Comment by daijh** [comment]
WebRTC is designed to work well with packet loss <10%, see below papers. The suggestion is to reduce the resolution, fps, bitrate, and choose VP9.

[1] Performance Evaluation of WebRTC based Video Conferencing 
https://wimnet.ee.columbia.edu/wp-content/uploads/2017/10/WebRTC-Performance.pdf
[2] Analysis and Design of the Google Congestion Control for Web Real-time Communication
https://c3lab.poliba.it/images/6/65/Gcc-analysis.pdf

QUIC is probably helpful, but definitely with the cost of latency.

**Comment by ashar02** [comment]
Thanks a lot for the help. I shall try the QUIC and let you know whether it is helpful in my network scenario or not.
