### ISSUE TITLE
Cluster scheduling strategy-round-used

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#835]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：

scene 1
1,Configure node scheduling strategy in cluster-manager/cluster-manager.toml to round-used
2,ps aux | grep webrtc-
Refresh the page multiple times
3,webrtc-agent  is not recycled
3，Expected ：

webrtc-agent Module recycling

**Comment by qwu16** [comment]
Cannot reproduce

**Comment by cisco66666** [comment]
Refresh the page multiple times
