### ISSUE TITLE
video-agent HA  Playback issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#839]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87
2，Reproduce step：
First scene
×1,,Device A starts all MCU modules
×2,Device B starts the video proxy and sets rabbitmq to point to device B
×3,User A connects to MCU, pub a stream, and mix to a mixed stream, sub a mix stream, the mix stream picture is normal and smooth
×4,Device A ：./bin/daemon.sh stop video-agent, 
The phenomenon at this time is that the picture in the mix returns to normal under the black screen. In device B, ps aux | grep video-is expected three processes, but it is found that the picture will be stuck, often stuck, and I looked at the cpu and Memory, found to be sufficient

3，Expected ：
After switching the video-agent, the screen is played normally, and there is no frequent lag

**Comment by qwu16** [comment]
Cannot reproduce
