### ISSUE TITLE
createsipcalls failed

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#840]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87

2，Reproduce step：
1,user sends createsipcalls request:failed
script2.js:221 POST https://webrtc90.sh.intel.com:3004/rooms/5f2122fe3ccc2e4f15bb31ee/sipcalls/ 500
send @ script2.js:221
createSipcalls @ script2.js:268
restCreateSipcalls @ script2.js:672
onclick @ (index):701

3，Expected ：
It is expected that createsipcalls is successful

**Comment by qwu16** [comment]
fixed by pr 841
