### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by Alex-YddeR** [open-webrtc-toolkit/owt-server#846]
We are getting below error while building the source. please let me know how to disable quic in building since quic transport is not working in build

make: *** [Release/obj.target/quic/addon.o] Error 1
quic.target.mk:158: recipe for target 'Release/obj.target/quic/QuicTransportServer.o' failed
make: *** [Release/obj.target/quic/QuicTransportServer.o] Error 1
make: Leaving directory '/home/ubuntu/mcurelease/owt-server-5.0-rc.1/source/agent/addons/quic/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-1032-aws
gyp ERR! command "/root/.nvm/versions/node/v10.21.0/bin/node" "/root/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "4" "--loglevel=error"
gyp ERR! cwd /home/ubuntu/mcurelease/owt-server-5.0-rc.1/source/agent/addons/quic
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 4 --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/home/ubuntu/mcurelease/owt-server-5.0-rc.1/scripts/build.js:133:5)
    at buildList.map (/home/ubuntu/mcurelease/owt-server-5.0-rc.1/scripts/build.js:161:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/ubuntu/mcurelease/owt-server-5.0-rc.1/scripts/build.js:156:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

Thanks

**Comment by Andy-CP-Cheng** [comment]
Edit  /master/source/agent/addons/quicIO/QuicTransport.cc line 74:
boost::shared_array<uint8_t> new_buffer;
to
boost::shared_array <char> new_buffer;

**Comment by Andy-CP-Cheng** [comment]
Edit /master/source/agent/addons/quicIO/QuicTransport.cc line 74:
boost::shared_array<uint8_t> new_buffer;
to
boost::shared_array <char> new_buffer;

**Comment by Andy-CP-Cheng** [comment]
Edit /master/source/agent/addons/quicIO/QuicTransport.cc line 74:
boost::shared_array<uint8_t> new_buffer;
to
boost::shared_array < char > new_buffer;

**Comment by Alex-YddeR** [comment]
Still we are getting same error. logs below

make: Entering directory '/home/ubuntu/mcurelease/owt-server-5.0-rc.1/source/agent/addons/quic/build'
  CXX(target) Release/obj.target/quic/QuicFactory.o
  CXX(target) Release/obj.target/quic/QuicTransportStream.o
  CXX(target) Release/obj.target/quic/QuicTransportServer.o
  CXX(target) Release/obj.target/quic/addon.o
In file included from ../QuicTransportStream.cc:7:0:
../QuicTransportStream.h:10:10: fatal error: owt/quic/quic_transport_stream_interface.h: No such file or directory
 #include "owt/quic/quic_transport_stream_interface.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
quic.target.mk:155: recipe for target 'Release/obj.target/quic/QuicTransportStream.o' failed
make: *** [Release/obj.target/quic/QuicTransportStream.o] Error 1
make: *** Waiting for unfinished jobs....
../QuicFactory.cc:8:10: fatal error: owt/quic/quic_transport_factory.h: No such file or directory
 #include "owt/quic/quic_transport_factory.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
quic.target.mk:155: recipe for target 'Release/obj.target/quic/QuicFactory.o' failed
make: *** [Release/obj.target/quic/QuicFactory.o] Error 1
In file included from ../QuicTransportConnection.h:18:0,
                 from ../QuicTransportServer.h:10,
                 from ../QuicTransportServer.cc:7:
../QuicTransportStream.h:10:10: fatal error: owt/quic/quic_transport_stream_interface.h: No such file or directory
 #include "owt/quic/quic_transport_stream_interface.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ../QuicTransportConnection.h:18:0,
                 from ../QuicTransportServer.h:10,
                 from ../addon.cc:7:
../QuicTransportStream.h:10:10: fatal error: owt/quic/quic_transport_stream_interface.h: No such file or directory
 #include "owt/quic/quic_transport_stream_interface.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
quic.target.mk:155: recipe for target 'Release/obj.target/quic/QuicTransportServer.o' failed
make: *** [Release/obj.target/quic/QuicTransportServer.o] Error 1
quic.target.mk:155: recipe for target 'Release/obj.target/quic/addon.o' failed
make: *** [Release/obj.target/quic/addon.o] Error 1
make: Leaving directory '/home/ubuntu/mcurelease/owt-server-5.0-rc.1/source/agent/addons/quic/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-1032-aws
gyp ERR! command "/root/.nvm/versions/node/v10.21.0/bin/node" "/root/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "4" "--loglevel=error"
gyp ERR! cwd /home/ubuntu/mcurelease/owt-server-5.0-rc.1/source/agent/addons/quic
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 4 --loglevel=error

**Comment by Alex-YddeR** [comment]
Dear Team,

Any help on the above 

Thanks

**Comment by ashar02** [comment]
I am also trying to compile from source... What value should be assigned to $QUIC_TRANSPORT_PACKAGE_URL_PREFIX in scripts/installCommonDeps.sh?

**Comment by jianjunz** [comment]
It's a similar issue as #844. PR #850 will fix this issue. Before it is merged, please try [this workaround](https://github.com/open-webrtc-toolkit/owt-server/issues/844#issuecomment-752868028).

Sorry for the trouble.
