### ISSUE TITLE
'Access-Control-Allow-Origin' issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#847]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87

2，Reproduce step：
After compiling and packaging mcu, useA connects to mcu，The error is as follows:
index.js:204 server connection failed: Error: connect_error:https://10.239.44.113:8080
    at owt.js:9
(anonymous) @ index.js:204
Promise.then (async)
(anonymous) @ index.js:143
req.onreadystatechange @ rest-sample.js:12
XMLHttpRequest.send (async)
send @ rest-sample.js:19
createToken @ rest-sample.js:79
window.onload @ index.js:141
load (async)
runSocketIOSample @ index.js:134
(anonymous) @ (index):52
(index):1 Access to XMLHttpRequest at 'https://10.239.44.113:8080/socket.io/?EIO=3&transport=polling&t=NRGvA3V' from origin 'https://webrtc90.sh.intel.com:3004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

3，Expected ：
useA connects to mcu normally

**Comment by javyxu** [comment]
> 1，Environment and platform：
> master，ubuntu18.04，software，chrome-Version 87
> 
> 2，Reproduce step：
> After compiling and packaging mcu, useA connects to mcu，The error is as follows:
> index.js:204 server connection failed: Error: connect_error:https://10.239.44.113:8080
> at owt.js:9
> (anonymous) @ index.js:204
> Promise.then (async)
> (anonymous) @ index.js:143
> req.onreadystatechange @ rest-sample.js:12
> XMLHttpRequest.send (async)
> send @ rest-sample.js:19
> createToken @ rest-sample.js:79
> window.onload @ index.js:141
> load (async)
> runSocketIOSample @ index.js:134
> (anonymous) @ (index):52
> (index):1 Access to XMLHttpRequest at 'https://10.239.44.113:8080/socket.io/?EIO=3&transport=polling&t=NRGvA3V' from origin 'https://webrtc90.sh.intel.com:3004' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> 
> 3，Expected ：
> useA connects to mcu normally

I also encountered the same problem. Have you solved it？

**Comment by javyxu** [comment]
@qwu16 After I changed the code according to the method you said and recompiled it, there is no cross-domain problem now, but the problem of "index.js:204 server connection failed: Error: connect_error:https://xxxxxx:8080
at owt.js:9" still exists. I wonder if you have a good method to solve it?

**Comment by qwu16** [comment]
@javyxu Please provide more detail description on your issue and how to reproduce it, how OWT is deployed.

**Comment by javyxu** [comment]
> @javyxu Please provide more detail description on your issue and how to reproduce it, how OWT is deployed.

Hello, I have solved the problem. The cause of this problem is that my browser version is too high (Chrome 87), it is OK to lower the version or change to another browser (Firefox, Safari). The fundamental reason is: certificate. Thank you very much！
