### ISSUE TITLE
sip issue

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#853]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87

2，Reproduce step：
scene 1
1,userA sends createsipcalls request to jitsi
2,jitsi Shows its own flow，mcu can also receive the stream of jitsi
But jitsi cannot receive the MCU picture
3，Expected ：
jitsi can receive the MCU picture

scene 2
1,User A sends stream to MCU through jitsi
2,jitsi Shows its own flow，mcu can also receive the stream of jitsi
But jitsi cannot receive the MCU picture
3，Expected ：
jitsi can receive the MCU picture

**Comment by starwarfan** [comment]
@qwu16, is this expected behaviour?
