### ISSUE TITLE
can not download quic

### ISSUE THREAD

**Issue by liyoubdu** [open-webrtc-toolkit/owt-server#867]
ubuntu 18.04.
git branch: master
error message:
command: scripts/installDepsUnattended.sh

error:
Failed to download prebuild QUIC SDK. Please download and compile QUIC SDK version 5df7581e55816cfc8eedd3cbe082a482b2445f28 from https://github.com/open-webrtc-toolkit/owt-deps-quic.

**Comment by jianjunz** [comment]
Duplicates #844 and #846. Fixed by #850.

**Comment by liyoubdu** [comment]
fixed
