### ISSUE TITLE
 quic module is not compiled

### ISSUE THREAD

**Issue by cisco66666** [open-webrtc-toolkit/owt-server#875]
1，Environment and platform：
master，ubuntu18.04，software，chrome-Version 87

2，Reproduce step：
 ./scripts/build.js --rebuild -t all --check
When compiling mcu, it was found that the quic module was not compiled

3，Expected ：
After compiling and packaging mcu, quic can be used normally

**Comment by jianjunz** [comment]
Fixed in the latest version. QUIC agent is disabled by default, but it can be enabled with flags.
