### ISSUE TITLE
Memory leak issue due to StaticTaskQueueFactory?

### ISSUE THREAD

**Issue by yjfxfjch** [open-webrtc-toolkit/owt-server#892]
Use `top` command,I find that webrtc node's memory grows up when it keeps running(Only one publisher and one subscriber communicating,and then no user in and out).Finally I locate to:
```
RtcAdapterImpl::RtcAdapterImpl()
    : m_taskQueueFactory(createStaticTaskQueueFactory())
    , m_taskQueue(std::make_shared<rtc::TaskQueue>(m_taskQueueFactory->CreateTaskQueue(
          "CallTaskQueue",
          webrtc::TaskQueueFactory::Priority::NORMAL)))
    , m_eventLog(std::make_shared<webrtc::RtcEventLogNull>())
{
}
```

`createStaticTaskQueueFactory()` causes it.

When use `webrtc::CreateDefaultTaskQueueFactory()`,everying is ok.I am not familiar with the implementation of `TaskQueueProxy`.What causes it?

Thx.

**Comment by yjfxfjch** [comment]
I have found why it causes memory leak.It is what I have fixed below:
```
// QueuedTaskProxy only execute when the owner shared_ptr exists
class QueuedTaskProxy : public webrtc::QueuedTask {
public:
    QueuedTaskProxy(std::unique_ptr<webrtc::QueuedTask> task, std::shared_ptr<int> owner)
        : m_task(std::move(task)), m_owner(owner) {}

    // Implements webrtc::QueuedTask
    bool Run() override
    {
        if (auto owner = m_owner.lock()) {
            // Only run when owner exists
            QueuedTask* raw = m_task.release();
            if (raw->Run()) {
                delete raw;
            }
        }
        return true;
    }
private:
    std::unique_ptr<webrtc::QueuedTask> m_task;
    std::weak_ptr<int> m_owner;
};
```
If `Run`  succeed,we should delete the `QueuedTask`.And `QueuedTaskProxy::Run ` may return false.In `webrtc::TaskQueueStdlib::ProcessTasks` :
```
    if (task.run_task_) {
      // process entry immediately then try again
      QueuedTask* release_ptr = task.run_task_.release();
      if (release_ptr->Run())
        delete release_ptr;

      // attempt to sleep again
      continue;
    }
```
The `release_ptr` is `QueuedTaskProxy `,so it needs to always return true.

**Comment by starwarfan** [comment]
Hi @yjfxfjch,
Your sharing is great, thank you very much.

**Comment by starwarfan** [comment]
The reason we use a staticTaskQueueFactory here is that we want to limit threads number in single process if there're lots of connections. Maybe there's a better way to do this.

**Comment by yjfxfjch** [comment]
I think single pc is the best way.With single pc,there are only a few threads.
