### ISSUE TITLE
server connection failed: Error: Unknown client protocol     at owt.js:9

### ISSUE THREAD

**Issue by anilk9096** [open-webrtc-toolkit/owt-server#904]
New Build on Ubuntu 18.04 LTS OWT-SERVER 4.3.X, configure ssl certificates but still getting 
server connection failed: Error: Unknown client protocol
    at owt.js:9

index.js:83 WebSocket connection to 'wss://xxxx.xxxx.com/socket.io/?EIO=3&transport=websocket&sid=FNtpjmtMfm_bZv55AAAB' failed: WebSocket is closed before the connection is established.
Portal running : 443
Chrome Version : 88 stable

**Comment by starwarfan** [comment]
Hi,
Looks like your client SDK version is higher than server's. What's your client SDK version?

**Comment by anilk9096** [comment]
Yes using client 4.3.x solved
