### ISSUE TITLE
Using mixed audio with forwarded video on same room

### ISSUE THREAD

**Issue by PonyHugger** [open-webrtc-toolkit/owt-server#952]
Hi!
In my use case, there is always one presenter, who is streaming audio and video, while the other participants are watching the video and are able to communicate with each other (and the presenter) via audio.
I'd like to know, if it's possible, to use mixed audio with a forwarded video stream on the same room. 

Thanks!

**Comment by tx-tech** [comment]
Hey, I am having the same scenario with you.  I am trying to test like this: the presenter publishes his audio and video, while other participants publish only audio without video.  They are all in mixed stream.  

If you already figured out how to do that, please share your findings with me.  Thanks in advance.

**Comment by starwarfan** [comment]
Hi, you can subscribe only audio from mix stream when subscribing only video from forwarded stream on client side. You can refer to JS doc's subscribeOption as an example. https://github.com/open-webrtc-toolkit/owt-client-javascript/blob/a3659b7756257b55772047a21c065b41af0998e0/src/sdk/conference/client.js#L494

**Comment by tx-tech** [comment]
@starwarfan thanks for your feedback.  Did you mean we can call subscribe for twice, one is only audio of mixed stream, the other is only video of forwarded stream?

**Comment by starwarfan** [comment]
> @starwarfan thanks for your feedback. Did you mean we can call subscribe for twice, one is only audio of mixed stream, the other is only video of forwarded stream?

Yes.

**Comment by PonyHugger** [comment]
@starwarfan Thank you very much!
