### ISSUE TITLE
failed to compile v5.0.x in ubuntu 20,  it seems owt-server can support boost 1.6,  but cannot support boost 1.7

### ISSUE THREAD

**Issue by inteltiger** [open-webrtc-toolkit/owt-server#968]
i failed to compile v5.0.x owt-server in ubuntu 20, refer to the bottom.  i did some investigation, it seems
owt-server depends on socket.io-client-cpp  
socket.io-client-cpp  depends on boost 1.67 and websocketpp

in ubuntu (desktop) 20, boost 1.7 is installed by default e.g. libboost-thread1.71.0.  
the file name path changed in boost 1.7,  there is a fix in websocketpp, but seems not helpful in my local build
https://github.com/zaphoyd/websocketpp/commit/c769c9238ad62178f506038178714a1c35aa2769  (seems not help)

socket.io-client-cpp master (aka 3.0) branch removed the dependency to boost  
https://github.com/socketio/socket.io-client-cpp/commit/af68bf3067ab45dc6a53261284e0da9afd21b636  
this might be a solution to fix too, i have not tested.

my build cmd is: $ scripts/build.js -c -t mcu 

the output is:

Following targets will be built:
 video-mixer-sw 
 video-transcoder-sw 
 video-analyzer-sw 
 internal-io 
 logger 
 media-frame-multicaster 
 audio 
 audio-ranker 
 webrtc-conn 
 webrtc-frame 
 avstream 
 gst-pipeline 
 sip 
Building addon - video-mixer-sw
make: Entering directory '/home/xiaoxime/my360/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/xiaoxime/my360/owt-server/source/agent/video/videoMixer/videoMixer_sw/build'
Finish addon - video-mixer-sw
Building addon - video-transcoder-sw
make: Entering directory '/home/xiaoxime/my360/owt-server/source/agent/video/videoTranscoder/videoTranscoder_sw/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/xiaoxime/my360/owt-server/source/agent/video/videoTranscoder/videoTranscoder_sw/build'
Finish addon - video-transcoder-sw
Building addon - video-analyzer-sw
make: Entering directory '/home/xiaoxime/my360/owt-server/source/agent/video/videoTranscoder/videoAnalyzer_sw/build'
make: Nothing to be done for 'all'.
make: Leaving directory '/home/xiaoxime/my360/owt-server/source/agent/video/videoTranscoder/videoAnalyzer_sw/build'
Finish addon - video-analyzer-sw
Building addon - internal-io
make: Entering directory '/home/xiaoxime/my360/owt-server/source/agent/addons/internalIO/build'
  CXX(target) Release/obj.target/internalIO/../../../core/owt_base/RawTransport.o
../../../../core/owt_base/RawTransport.cpp: In member function ‘void owt_base::RawTransport<prot>::createConnection(const string&, uint32_t)’:
../../../../core/owt_base/RawTransport.cpp:166:76: error: no matching function for call to ‘boost::asio::ssl::context::context(boost::asio::io_service&, boost::asio::ssl::context_base::method)’
                     m_service->service(), boost::asio::ssl::context::sslv23));
                                                                            ^
In file included from /usr/include/boost/asio/ssl/context.hpp:757:0,
                 from /usr/include/boost/asio/ssl.hpp:18,
                 from ../../../../core/owt_base/RawTransport.h:9,
                 from ../../../../core/owt_base/RawTransport.cpp:7:
/usr/include/boost/asio/ssl/impl/context.ipp:371:1: note: candidate: boost::asio::ssl::context::context(boost::asio::ssl::context&&)
 context::context(context&& other)
 ^~~~~~~
/usr/include/boost/asio/ssl/impl/context.ipp:371:1: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/asio/ssl/impl/context.ipp:63:1: note: candidate: boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)
 context::context(context::method m)
 ^~~~~~~
/usr/include/boost/asio/ssl/impl/context.ipp:63:1: note:   candidate expects 1 argument, 2 provided
../../../../core/owt_base/RawTransport.cpp: In member function ‘void owt_base::RawTransport<prot>::listenTo(uint32_t)’:
../../../../core/owt_base/RawTransport.cpp:337:76: error: no matching function for call to ‘boost::asio::ssl::context::context(boost::asio::io_service&, boost::asio::ssl::context_base::method)’
                     m_service->service(), boost::asio::ssl::context::sslv23));
                                                                            ^
In file included from /usr/include/boost/asio/ssl/context.hpp:757:0,
                 from /usr/include/boost/asio/ssl.hpp:18,
                 from ../../../../core/owt_base/RawTransport.h:9,
                 from ../../../../core/owt_base/RawTransport.cpp:7:
/usr/include/boost/asio/ssl/impl/context.ipp:371:1: note: candidate: boost::asio::ssl::context::context(boost::asio::ssl::context&&)
 context::context(context&& other)
 ^~~~~~~
/usr/include/boost/asio/ssl/impl/context.ipp:371:1: note:   candidate expects 1 argument, 2 provided
/usr/include/boost/asio/ssl/impl/context.ipp:63:1: note: candidate: boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)
 context::context(context::method m)
 ^~~~~~~
/usr/include/boost/asio/ssl/impl/context.ipp:63:1: note:   candidate expects 1 argument, 2 provided
make: *** [internalIO.target.mk:128: Release/obj.target/internalIO/../../../core/owt_base/RawTransport.o] Error 1
make: Leaving directory '/home/xiaoxime/my360/owt-server/source/agent/addons/internalIO/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/xiaoxime/.nvm/versions/node/v10.21.0/lib/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.8.0-44-generic
gyp ERR! command "/home/xiaoxime/.nvm/versions/node/v10.21.0/bin/node" "/home/xiaoxime/.nvm/versions/node/v10.21.0/bin/node-gyp" "build" "-j" "16" "--loglevel=error"
gyp ERR! cwd /home/xiaoxime/my360/owt-server/source/agent/addons/internalIO
gyp ERR! node -v v10.21.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
child_process.js:669
    throw err;
    ^

Error: Command failed: node-gyp build -j 16 --loglevel=error
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at buildTarget (/home/xiaoxime/my360/owt-server/scripts/build.js:133:5)
    at buildList.map (/home/xiaoxime/my360/owt-server/scripts/build.js:161:10)
    at Array.map (<anonymous>)
    at Object.<anonymous> (/home/xiaoxime/my360/owt-server/scripts/build.js:156:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

**Comment by taste1981** [comment]
@inteltiger owt-server is not using the cpp version of socket.io implemetation and it does not need to.  
You're actually reporting RawTransport implementation only compiles with boost 1.65 and below and we're aware of this.

Any reason you must use ubuntu20.04? If there's strong requirment, we will add support for ubuntu 20.04.

**Comment by inteltiger** [comment]
mainly for security concern. thanks

**Comment by taste1981** [comment]
Fixed by #969
