### ISSUE TITLE
Latest code build error

### ISSUE THREAD

**Issue by hakicode** [open-webrtc-toolkit/owt-server#973]
Hope anyone can check the code build on the new device.
it has a lot of bugs, and I can't build it.

**Comment by hakicode** [comment]
$ scripts/installDepsUnattended.sh

~/open-webrtc-toolkit/owt-server/third_party/quic-transport ~/open-webrtc-toolkit/owt-server
/linux/306912b0257df19f0327a46a9d41d88b629826d0.zip: Scheme missing.

**Comment by PonyHugger** [comment]
I am having the same problem on V5.0.

**Comment by hakicode** [comment]
@starwarfan thank you so much.

**Comment by peererror** [comment]
I having same issue is there any special command to compile
