### ISSUE TITLE
Set proxy in the install script

### ISSUE THREAD

**Issue by tianjunwork** [open-webrtc-toolkit/owt-server#98]
When I run scripts/installDepsUnattended.sh, it failed to install:
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to https://registry.npmjs.org/node-gyp failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

Could you add proxy in the script? If there is a system proxy parameter, it will use it automatically. 
And can I use owt-server inside a company intranet? Any other configurations?
Thank you.

**Comment by taste1981** [comment]
the script does include "check_proxy" that checks your https_proxy env and configs npm proxy.

**Comment by tianjunwork** [comment]
Thx. It works after adding env.
