### ISSUE TITLE
owt audio 不支持AAC-HE和AAC-HEv2 解码

### ISSUE THREAD

**Issue by zhangyihui360-owt** [open-webrtc-toolkit/owt-server#984]
由于项目需求，输入RTMP h264 + AAC-HE/AAC-HEv2  #[混流输出，audio模块解码失败崩溃，定位audio模块ffmpeg调用解码失败崩溃，ffmpeg更换libfdk_aac之后解码仍然失败。输入音频格式更换成AAC-LC正常解码混流输出；### [](url)

**Comment by daijh** [comment]
extradata is not sent from streaming agent to audio agent.

**Comment by zhangyihui360-owt** [comment]
Thank you very much for OWT's answer. The problem has been solved.
