### ISSUE TITLE
WebRTC failed to build

### ISSUE THREAD

**Issue by tianjunwork** [open-webrtc-toolkit/owt-server#99]
ninja: Entering directory `out'
[394/1331] CXX obj/third_party/libyuv/libyuv_internal/row_any.o
../third_party/libyuv/source/row_any.cc: In function ‘void libyuv::HalfFloatRow_Any_SSE2(const uint16*, uint16*, float, int)’:
../third_party/libyuv/source/row_any.cc:724:23: warning: ‘memset’ used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]
     memset(temp, 0, 32); /* for msan */                                      \
                       ^
../third_party/libyuv/source/row_any.cc:736:1: note: in expansion of macro ‘ANY11P16’
 ANY11P16(HalfFloatRow_Any_SSE2, HalfFloatRow_SSE2, float, 2, 2, 7)
 ^~~~~~~~
../third_party/libyuv/source/row_any.cc: In function ‘void libyuv::HalfFloatRow_Any_AVX2(const uint16*, uint16*, float, int)’:
../third_party/libyuv/source/row_any.cc:724:23: warning: ‘memset’ used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]
     memset(temp, 0, 32); /* for msan */                                      \
                       ^
../third_party/libyuv/source/row_any.cc:739:1: note: in expansion of macro ‘ANY11P16’
 ANY11P16(HalfFloatRow_Any_AVX2, HalfFloatRow_AVX2, float, 2, 2, 15)
 ^~~~~~~~
[459/1331] CC obj/webrtc/common_audio/common_audio_c/vad_core.o
FAILED: obj/webrtc/common_audio/common_audio_c/vad_core.o
gcc -MMD -MF obj/webrtc/common_audio/common_audio_c/vad_core.o.d -DV8_DEPRECATION_WARNINGS -DUSE_UDEV -DUSE_AURA=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -DCHROMIUM_BUILD -DENABLE_MEDIA_ROUTER=1 -DFIELDTRIAL_TESTING_ENABLED -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DWEBRTC_ENABLE_PROTOBUF=0 -DWEBRTC_INCLUDE_INTERNAL_AUDIO_DEVICE -DEXPAT_RELATIVE_PATH -DWEBRTC_POSIX -DWEBRTC_LINUX -I.. -Igen -I../webrtc/common_audio/resampler/include -I../webrtc/common_audio/signal_processing/include -I../webrtc/common_audio/vad/include -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -funwind-tables -fPIC -pipe -m64 -march=x86-64 -pthread -Wall -Wno-unused-local-typedefs -Wno-maybe-uninitialized -Wno-missing-field-initializers -Wno-unused-parameter -O2 -fno-ident -fdata-sections -ffunction-sections -fomit-frame-pointer -g0 -fvisibility=hidden -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-strict-overflow  -c ../webrtc/common_audio/vad/vad_core.c -o obj/webrtc/common_audio/common_audio_c/vad_core.o
../webrtc/common_audio/vad/vad_core.c:118:1: error: attributes should be specified before the declarator in a function definition
 static inline int32_t OverflowingMulS16ByS32ToS32(int16_t a, int32_t b)
 ^~~~~~
../webrtc/common_audio/vad/vad_core.c: In function ‘GmmProbability’:
../webrtc/common_audio/vad/vad_core.c:391:22: warning: implicit declaration of function ‘OverflowingMulS16ByS32ToS32’ [-Wimplicit-function-declaration]
           tmp2_s32 = OverflowingMulS16ByS32ToS32(tmp_s16, tmp1_s32);
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[523/1331] CXX obj/webrtc/base/rtc_task_queue/task_queue_libevent.o
../webrtc/base/task_queue_libevent.cc: In destructor ‘rtc::TaskQueue::PostAndReplyTask::~PostAndReplyTask()’:
../webrtc/base/task_queue_libevent.cc:182:10: warning: ignoring return value of ‘ssize_t write(int, const void*, size_t)’, declared with attribute warn_unused_result [-Wunused-result]
     write(reply_pipe_, &message, sizeof(message));
     ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[528/1331] CXX obj/webrtc/modules/audio_coding/neteq/neteq_impl.o
../webrtc/modules/audio_coding/neteq/neteq_impl.cc: In member function ‘int webrtc::NetEqImpl::GetAudioInternal(webrtc::AudioFrame*, bool*)’:
../webrtc/modules/audio_coding/neteq/neteq_impl.cc:975:41: warning: this statement may fall through [-Wimplicit-fallthrough=]
       sync_buffer_->IncreaseEndTimestamp(
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
           static_cast<uint32_t>(output_size_samples_));
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../webrtc/modules/audio_coding/neteq/neteq_impl.cc:981:5: note: here
     case kAudioRepetition: {
     ^~~~
[532/1331] CC obj/third_party/libvpx/libvpx_intrinsics_sse2/fwd_txfm_sse2.o
ninja: build stopped: subcommand failed.

**Comment by sunjun** [comment]
same error here
../webrtc/common_audio/vad/vad_core.c:118:1: error: attributes should be specified before the declarator in a function definition
static inline int32_t OverflowingMulS16ByS32ToS32(int16_t a, int32_t b)

**Comment by tianjunwork** [comment]
@sunjun build pass now. I checked it today.

**Comment by sunjun** [comment]
@tianjunwork thank you, maybe I am use ubuntu 19.04 cause this error, I will change 18.04 retry
